var musicLyricsArray = [
    "I can't believe that when I breathe There's something good inside of me Just one good thing inside So close to me, that memory Of that one good thing inside of me Just one good thing inside of me, yeah If I ran out the backdoor, nobody would stop me But where would I go? 'Cause I ain't ever had a real home So what do I know? So I could keep running, hide until they find me But what would that do? If they could only know what I knew What would it prove? I should've seen the writing on the wall Instead, I'm left to fall 'Cause the longer I'm away The more we stay the same Looking back, \
    would've thought I knew it all Instead, I'm left to fall, did I throw it all away? I can't believe that when I breathe There's something good inside of me Just one good thing inside So close to me, that memory Of that one good thing inside of me Just one good thing inside of me, yeah Don't you know, little boy, they'll lay you to waste, man? Little do they know every song has a lifespan Never taken one, but I'm taking my last chance To hold all we know and let go with both hands So don't you know the clouds are made from concrete? Right through the stone, can you hear my heartbeat? Beats through my bones like the \
    memory left me Not for a second or a minute when I dream I wanna go home, like the home that I keep You can dig six or 66 feet We could live forever, still your misery missed me Hold this song together with a bottle of whiskey Look into the mirror at the lines that time drew See them painted white and the eyes that shine through My heart beats heavy in an open chest And I wanna say goodbye, but there's nobody left I can't believe that when I breathe There's something good inside of me Just one good thing inside So close to me, that memory Of that one good thing inside of me Just one good thing inside of me, yeah I \
    broke it all and I put it to test Put your hand to mine and feel this emptiness There's no beat in my chest 'cause there's nothing left No, it ain't goodbye, it's a last caress What's another dream? You can hardly sleep Can you believe bad things only happen to me? God knows one day you will finally see That scars will heal but were meant to bleed Did you realized I would lie for you? Please, have my last breath, I would die for you I know I'm no good, but my heart beats true You know I'm gonna fight, though I might be scared to lose You took me in and I fucked it up again An empty promise? No, I won't pretend 'Cause \
    in the end, we need someone to solve 'em Nobody can fix me if I'm part of the problem I can't believe that when I breathe There's something good inside of me Just one good thing inside So close to me, that memory Of that one good thing inside of me Just one good thing inside of me, yeah",
    "I am a lion and I want to be free Do you see a lion when you look inside of me? Outside the window just to watch you as you sleep 'Cause I am a lion, born from things you cannot be How can I sleep at night? There's a war inside my head I found a lion hidden right beneath my bed I will not hide myself from the tears that you have shed 'Cause I am a lion, and you are dead Here's a story of everything we'll ever be You can hide but some of us can never leave And if you go I don't need those little things They remind me of all our little dreams Can you hear the words, all I can say We can watch the world even if they walk \
    away Forget about tomorrow, tomorrow is today You were born a lion, and a lion you will stay I am a lion and I want to be free Do you see a lion when you look inside of me? Outside the window just to watch you as you sleep 'Cause I am a lion, born from things you cannot be Remember an army of all those little kids Livin' life like they only get a little bit It's hard to fight when you're born in the middle-end I'd rather die, won't watch you givin' in I'm sorry daughter, but you're father's not the same I can look into your eyes and I swear that I will change But tomorrow is tomorrow, so forgive me if I stay You can hide\
    beneath the covers while I hide behind the pain After all, only so much we can say Words can lose their meaning, once we walk away Promise me that you'll love me, watch me as I fade I'll give you all the things that these lions never gave The hands on the clock and the things we cannot change Is tearin' out the pieces and take back what I made If there's one thing I'd keep, it's you that I would save 'Cause I am just a lion, and a lion I will stay I am a lion and I want to be free Do you see a lion when you look inside of me? Outside the window just to watch you as you sleep 'Cause I am a lion, born from things you cannot \
    be Hey! I never meant to let go You're all I want, and you're all I ever wanna know Can't hide in the attic of a pretty home Of a pretty home, of a pretty home Hey! I never meant to let go You're all I want, and you're all I ever wanna know Can't hide in the attic of a pretty home Of a pretty home, of a pretty home I am a lion and I want to be free Do you see a lion when you look inside of me? Outside the window just to watch you as you sleep 'Cause I am a lion, born from things you cannot be",
    "Hold on to me love, You know I can't stay long, All I wanted to say was, I love you and I'm not afraid, Can you hear me?, Can you feel me in your arms, Holding my last breath, Safe inside myself, Are all my thoughts of you, Sweet raptured light,, It ends here tonight., I'll miss the winter, A world of fragile things, Look for me in the white forest, Hiding in a hollow tree (come find me), I know you hear me,, I can taste it in your tears., Holding my last breath, Safe inside myself, Are all my thoughts of you, Sweet raptured light,, It ends here tonight., Closing your eyes to disappear, You pray your dreams will \
    leave you here,, But still you wake and know the truth -, No one's there., Say goodnight, don't be afraid, Calling me, calling me, as you fade to black., Holding my last breath, (Don't be afraid) Safe inside myself, (Holding me) Are all my thoughts of you?, Sweet raptured light,, It ends here tonight., Holding my last breath, Safe inside myself, Are all my thoughts of you?, Sweet raptured light,, It ends here tonight., Holding my last breath",
    "No lyrics are available.",
    "Mr. Sandman, bring me a dream (bung, bung, bung, bung) Make him the cutest that I've ever seen (bung, bung, bung, bung) Give him two lips like roses and clover (bung, bung, bung, bung) Then tell him that his lonesome nights are over Sandman, I'm so alone (bung, bung, bung, bung) Don't have nobody to call my own (bung, bung, bung, bung) Please turn on your magic beam Mr. Sandman, bring me a dream Mr. Sandman, bring me a dream Make him the cutest that I've ever seen Give him the word that I'm not a rover Then tell him that his lonesome nights are over Sandman, I'm so alone Don't have nobody to call my own Please turn on your \
    magic beam Mr. Sandman, bring me a dream Mr. Sandman (yes) bring us a dream Give him a pair of eyes with a come-hither gleam Give him a lonely heart like Pagliacci And lots of wavy hair like Liberace Mr. Sandman, someone to hold (someone to hold) Would be so peachy before we're too old So please turn on your magic beam Mr. Sandman, bring us, please, please, please Mr. Sandman, bring us a dream",
    "Hey (hey), I'm your life I'm the one who takes you there Hey (hey), I'm your life I'm the one who cares They (they), they betray I'm your only true friend now They (they), they'll betray I'm forever there I'm your dream, make you real I'm your eyes when you must steal I'm your pain when you can't feel Sad but true I'm your dream, mind astray I'm your eyes while you're away I'm your pain while you repay You know it's sad but true Sad but true You (you), you're my mask You're my cover, my shelter You (you), you're my mask You're the one who's blamed Do (do), do my work Do my dirty work, scapegoat Do (do), do my deeds For \
    you're the one who's shamed I'm your dream, make you real I'm your eyes when you must steal I'm your pain when you can't feel Sad but true I'm your dream, mind astray I'm your eyes while you're away I'm your pain while you repay You know it's sad but true Sad but true I'm your dream, I'm your eyes I'm your pain I'm your dream (I'm your dream) I'm your eyes (I'm your eyes) I'm your pain (I'm your pain) You know it's sad but true Hate (hate), I'm your hate I'm your hate when you want love Pay (pay), pay the price Pay for nothing's fair Hey (hey), I'm your life I'm the one who took you there Hey (hey), I'm your life And I no \
    longer care I'm your dream, make you real I'm your eyes when you must steal I'm your pain when you can't feel Sad but true I'm your truth, telling lies I'm your reasoned alibis I'm inside, open your eyes I'm you Sad but true",
    "I let it fall, my heart And as it fell, you rose to claim it It was dark, and I was over Until you kissed my lips and you saved me My hands, they were strong But my knees were far too weak To stand in your arms Without falling to your feet But there's a side to you That I never knew, never knew All the things you'd say They were never true, never true And the games you'd play You would always win, always win But I set fire to the rain Watched it pour as I touched your face Well, it burned while I cried 'Cause I heard it screamin' out your name Your name You might also like HISS Megan Thee Stallion Big Foot Nicki Minaj ​ballad of a \
    homeschooled girl Olivia Rodrigo When I lay with you I could stay there, close my eyes Feel you here forever You and me together, nothing is better 'Cause there's a side to you That I never knew, never knew All the things you'd say They were never true, never true And the games you'd play You would always win, always win But I set fire to the rain Watched it pour as I touched your face Well, it burned while I cried 'Cause I heard it screamin' out your name Your name I set fire to the rain And I threw us into the flames When we fell, somethin' died 'Cause I knew that that was the last time The last time Sometimes, I wake up by the \
    door That heart you caught must be waitin' for you Even now, when we're already over I can't help myself from lookin' for you I set fire to the rain Watched it pour as I touched your face Well, it burned while I cried 'Cause I heard it screamin' out your name Your name I set fire to the rain And I threw us into the flames When we fell, somethin' died 'Cause I knew that that was the last time The last time Oh Oh, no Let it burn Oh Let it burn Let it burn",
    "Can you hear the silence? Can you see the dark? Can you fix the broken? Can you feel, can you feel my heart? Can you help the hopeless? Well, I'm begging on my knees Can you save my bastard soul? Will you wait for me? I'm sorry, brothers, so sorry, lover Forgive me, father, I love you, mother Can you hear the silence? Can you see the dark? Can you fix the broken? Can you feel my heart? Can you feel my heart? I'm scared to get close, and I hate being alone I long for that feeling to not feel at all The higher I get, the lower I'll sink I can't drown my demons, they know how to swim I'm scared to get close, and I hate being \
    alone I long for that feeling to not feel at all The higher I get, the lower I'll sink I can't drown my demons, they know how to swim I'm scared to get close, and I hate being alone I long for that feeling to not feel at all The higher I get, the lower I'll sink I can't drown my demons, they know how to swim Can you feel my heart? Can you hear the silence? Can you see the dark? Can you fix the broken? Can you feel, can you feel my heart?",
    "Take me down to the river bend Take me down to the fighting end Wash the poison from off my skin Show me how to be whole again Fly me up on a silver wing Past the black where the sirens sing Warm me up in a nova's glow And drop me down to the dream below 'Cause I'm only a crack in this castle of glass Hardly anything there for you to see For you to see Bring me home in a blinding dream Through the secrets that I have seen Wash the sorrow from off my skin And show me how to be whole again 'Cause I'm only a crack in this castle of glass Hardly anything there for you to see For you to see 'Cause I'm only a crack in this castle \
    of glass Hardly anything else I need to be 'Cause I'm only a crack in this castle of glass Hardly anything there for you to see For you to see For you to see",
    "Sunlight was the only thing that felt right before I came here But inside it feels like it keeps raining And every drop is like the tears we couldn't cry Because outside we were all alone But this place gave us something that somehow made us strong If there's a place inside this world Where hopes and dreams are not yet lost We'll stand as one against these walls And fight this fight forevermore Sometimes I feel this anger changing slowly in to A monster that keeps on creeping under And I don't think that I can take anymore I need your help like never before But can you hear me call? If there's a place inside this world Where \
    hopes and dreams are not yet lost We'll stand as one against these walls And fight this fight forevermore If there's a place inside this world Where we must go back to once more Until the day we find that place We're not alone When things go bad When things go wrong When on the verge of letting go There's something that I really want you to know When things go bad When things go wrong When on the verge of letting go There's something that I really want you to know You're not alone You're not alone anymore You're not alone You're not alone anymore If there's a place inside this world Where hopes and dreams are not yet lost \
    We'll stand as one against these walls And fight this fight forevermore If there's a place inside this world Where we must go back to once more Until the day we find that place We're not alone We're not alone When things go bad When things go wrong When on the verge of letting go There's something that I really want you to know",
    "Hey-o, here comes the danger up in this club When we get started, man, we ain't gon' stop We gon' turn it out 'til it gets too hot Everybody sing, hey-o Tell 'em turn it up 'til they can't no more Let's get this thing shakin' like a disco ball This is your last warning, a courtesy call Hey-o, here comes the danger up in this club When we get started, man, we ain't gon' stop We gon' turn it out 'til it gets too hot Everybody sing, hey-o Tell 'em turn it up 'til they can't no more Let's get this thing shakin' like a disco ball This is your last warning, a courtesy call I am not afraid of the storm that comes my way When it \
    hits it shakes me to the core And makes me stronger than before It's not a question about trust But will you stand with us? Can you feel it? Make it real and I think it might wash away tonight Awaken from this never ending fight It takes more than meets the eye This war we're fighting it's not just rotting Hey-o, here comes the danger up in this club When we get started, man, we ain't gon' stop We gon' turn it out 'til it gets too hot Everybody sing, hey-o Tell 'em turn it up 'til they can't no more Let's get this thing shakin' like a disco ball This is your last warning, a courtesy call There's a rumble in the floor So get\
    prepared for war When it hits it'll knock you to the ground When it shakes up everything around But survival is a must So will you stand with us? Can you feel it? Make it real and (make me feel it) I think it might wash away tonight Awaken from this never ending fight It takes more than meets the eye This war we're fighting it's not just rotting Hey-o, here comes the danger up in this club When we get started, man, we ain't gon' stop We gon' turn it out 'til it gets too hot Everybody sing, hey-o Tell 'em turn it up 'til they can't no more Let's get this thing shakin' like a disco ball This is your last warning, a courtesy \
    call Hey-o, here comes the danger up in this club When we get started, man, we ain't gon' stop We gon' turn it out 'til it gets too hot Everybody sing, hey-o Tell 'em turn it up 'til they can't no more Let's get this thing shakin' like a disco ball This is your last warning, a courtesy call",
    "No lyrics are available",
    "No lyrics are available",
    "No lyrics are available",
    "Look, I was gonna go easy on you not to hurt your feelings But I'm only going to get this one chance (six minutes-, six minutes-) Something's wrong, I can feel it (six minutes, Slim Shady, you're on!) Just a feeling I've got, like something's about to happen, but I don't know what If that means what I think it means, we're in trouble, big trouble And if he is as bananas as you say, I'm not taking any chances You are just what the doc ordered I'm beginnin' to feel like a Rap God, Rap God All my people from the front to the back nod, back nod Now, who thinks their arms are long enough to slap box, slap box? They said I rap like\
    a robot, so call me Rap-bot But for me to rap like a computer, it must be in my genes I got a laptop in my back pocket My pen'll go off when I half-cock it Got a fat knot from that rap profit Made a livin' and a killin' off it Ever since Bill Clinton was still in office With Monica Lewinsky feelin' on his nutsack I'm an MC still as honest But as rude and as indecent as all hell Syllables, skill-a-holic (kill 'em all with) This flippity dippity-hippity hip-hop You don't really wanna get into a pissin' match With this rappity brat, packin' a MAC in the back of the Ac' Backpack rap crap, yap-yap, yackety-yack And at the exact same \
    time, I attempt these lyrical acrobat stunts while I'm practicin' that I'll still be able to break a motherfuckin' table Over the back of a couple of faggots and crack it in half Only realized it was ironic, I was signed to Aftermath after the fact How could I not blow? All I do is drop F-bombs Feel my wrath of attack Rappers are havin' a rough time period, here's a maxi pad It's actually disastrously bad for the wack While I'm masterfully constructing this masterpièce 'Cause I'm beginnin' to feel like a Rap God, Rap God All my people from the front to the back nod, back nod Now, who thinks their arms are long enough to slap box,\
    slap box? Let me show you maintainin' this shit ain't that hard, that hard Everybody want the key and the secret to rap immortality like Ι have got Well, to be truthful the blueprint's Simply rage and youthful exuberance Everybody loves to root for a nuisance Hit the Earth like an asteroid Did nothing but shoot for the Moon since (pew!) MCs get taken to school with this music 'Cause I use it as a vehicle to Bus the rhyme Now I lead a new school full of students Me? I'm a product of Rakim Lakim Shabazz, 2Pac, N.W.A, Cube, hey Doc, Ren Yella, Eazy, thank you, they got Slim Inspired enough to one day grow up, blow up and be in a \
    position To meet Run-D.M.C., induct them Into the motherfuckin' Rock and Roll Hall of Fame Even though I'll walk in the church and burst in a ball of flames Only Hall of Fame I'll be inducted in is the alcohol of fame On the wall of shame You fags think it's all a game, 'til I walk a flock of flames Off a plank and, tell me what in the fuck are you thinkin'? Little gay-lookin' boy So gay, I can barely say it with a straight face, lookin' boy (ha-ha!) You're witnessin' a mass-occur Like you're watching a church gathering take place, lookin' boy Oy vey, that boy's gay! That's all they say, lookin' boy You get a thumbs up, pat on \
    the back And a Way to go from your label every day, lookin' boy Hey, lookin' boy! What you say, lookin' boy? I get a Hell, yeah from Dre, lookin' boy I'ma work for everything I have, never asked nobody for shit Get outta my face, lookin' boy! Basically, boy, you're never gonna be capable Of keepin' up with the same pace, lookin' boy, 'cause- I'm beginnin' to feel like a Rap God, Rap God All my people from the front to the back nod, back nod The way I'm racin' around the track, call me NASCAR, NASCAR Dale Earnhardt of the trailer park, the White Trash God Kneel before General Zod This planet's Krypton-, no, Asgard, Asgard So \
    you'll be Thor and I'll be Odin You rodent, I'm omnipotent Let off, then I'm reloadin' Immediately with these bombs I'm totin' And I should not be woken I'm the walkin' dead, but I'm just a talkin' head, a zombie floatin' But I got your mom deep-throatin' I'm out my Ramen Noodle We have nothin' in common, poodle I'm a Doberman, pinch yourself in the arm and pay homage, pupil It's me, my honesty's brutal But it's honestly futile if I don't utilize what I do though For good at least once in a while So I wanna make sure somewhere in this chicken scratch I scribble and doodle enough rhymes To maybe try to help get some people \
    through tough times But I gotta keep a few punchlines Just in case 'cause even you unsigned Rappers are hungry lookin' at me like it's lunchtime I know there was a time where once I Was king of the underground But I still rap like I'm on my Pharoahe Monch grind So I crunch rhymes, but sometimes when you combine Appeal with the skin color of mine You get too big and here they come tryin' To censor you like that one line I said on I'm Back from The Mathers LP 1 when I Tried to say I'll take seven kids from Columbine Put 'em all in a line, add an AK-47, a revolver and a .9 See if I get away with it now that I ain't as big as I was, \
    but I'm Morphin' into an immortal, comin' through the portal You're stuck in a time warp from 2004 though And I don't know what the fuck that you rhyme for You're pointless as Rapunzel with fuckin' cornrows You write normal? Fuck being normal! And I just bought a new raygun from the future Just to come and shoot ya, like when Fabolous made Ray J mad 'Cause Fab said he looked like a fag at Mayweather's pad Singin' to a man while he played piano Man, oh man, that was a 24-7 special on the cable channel So Ray J went straight to the radio station The very next day, Hey Fab, I'ma kill you! Lyrics comin' at you at supersonic speed \
    (J.J. Fad) Uh, summa-lumma, dooma-lumma, you assumin' I'm a human What I gotta do to get it through to you I'm superhuman? Innovative and I'm made of rubber so that anything You say is ricochetin' off of me, and it'll glue to you and I'm devastating, more than ever demonstrating How to give a motherfuckin' audience a feeling like it's levitating Never fading, and I know the haters are forever waiting For the day that they can say I fell off, they'll be celebrating 'Cause I know the way to get 'em motivated I make elevating music, you make elevator music Oh, he's too mainstream Well, that's what they do when they get jealous, they \
    confuse it It's not hip-hop, it's pop,  'cause I found a hella way to fuse it With rock, shock rap with Doc Throw on Lose Yourself and make 'em lose it I don't know how to make songs like that I don't know what words to use Let me know when it occurs to you While I'm rippin' any one of these verses that versus you It's curtains, I'm inadvertently hurtin' you How many verses I gotta murder to Prove that if you were half as nice, your songs you could sacrifice virgins too? Ugh, school flunky, pill junkie But look at the accolades these skills brung me Full of myself, but still hungry I bully myself 'cause I make me do what I put \
    my mind to And I'm a million leagues above you Ill when I speak in tongues, but it's still tongue-in-cheek, fuck you I'm drunk, so, Satan, take the fucking wheel I'ma sleep in the front seat Bumpin' Heavy D and the Boyz, still Chunky but Funky But in my head, there's something I can feel tugging and struggling Angels fight with devils and here's what they want from me They're askin' me to eliminate some of the women hate But if you take into consideration the bitter hatred I have, then you may be a little patient And more sympathetic to the situation And understand the discrimination But fuck it, life's handin' you lemons? \
    Make lemonade then! But if I can't batter the women How the fuck am I supposed to bake them a cake then? Don't mistake him for Satan; it's a fatal mistake If you think I need to be overseas and take a vacation To trip a broad, and make her fall on her face and Don't be a retard, be a king? Think not Why be a king when you can be a god?",
    "How can you see into my eyes Like open doors? Leading you down into my core Where I've become so numb Without a soul (Soul) My spirit's sleeping somewhere cold Until you find it there and lead it back home Wake me up Wake me up inside I can't wake up Wake me up inside Save me Call my name and save me from the dark Wake me up Bid my blood to run I can't wake up Before I come undone Save me Save me from the nothing I've become Now that I know what I'm without You can't just leave me (Ooh, oh) Breathe into me and make me real (Make me real) Bring (Bring) me (Me) to life You might also like Big Foot Nicki Minaj HISS Megan Thee \
    Stallion Taylor Swift Wake me up Wake me up inside I can't wake up Wake me up inside Save me Call my name and save me from the dark Wake me up Bid my blood to run I can't wake up Before I come undone Save me Save me from the nothing I've become Bring me to life I've been livin' a lie There's nothing inside Bring me to life Frozen inside (Frozen inside) Without your touch (Without your love) Without your love, darling Only you (Only you) are the life (Life) among the dead All this time, I can't believe I couldn't see Kept in the dark, but you were there in front of me I've been sleeping a thousand years, it seems Got to open \
    my eyes to everything Without a thought, without a voice, without a soul Don't let me die here There must be something more Bring me to life Wake me up Wake me up inside I can't wake up Wake me up inside Save me Call my name and save me from the dark Wake me up Bid my blood to run I can't wake up Before I come undone Save me Save me from the nothing I've become Bring me to life I've been living a lie (Bring me to life) There's nothing inside (There's nothing inside) Bring me to life",
    "Oh, it's just me, myself and I Solo ride until I die 'Cause I got me for life Oh I don't need a hand to hold Even when the night is cold I got that fire in my soul And as far as I can see I just need privacy Plus a whole lot of tree, fuck all this modesty I just need space to do me get a world that they're tryna see A Stella Maxwell right beside of me A Ferrari I'm buyin' three A closet of Saint Laurent, get what I want when I want 'Cause this hunger is driving me, yeah I just need to be alone, I just need to be at home Understand what I'm speaking on if time is money I need a loan But regardless I'll always keep keepin' on \
    Fuck fake friends, we don't take L's we just make M's While y'all follow, we just make trends I'm right back to work when that break ends Oh, it's just me, myself and I Solo ride until I die 'Cause I got me for life (Got me for life, yeah) Oh I don't need a hand to hold Even when the night is cold I got that fire in my soul I don't need anything to get me through the night Except the beat that's in my heart Yeah, it's keeping me alive (Keeps me alive) I don't need anything to make me satisfied (You know) 'Cause the music fills me good and it gets me every time Yeah, and I don't like talking to strangers So get the fuck off me \
    I'm anxious I'm tryna be cool but I may just go ape shit Say fuck y'all to all of y'all faces It changes though now that I'm famous Everyone knows how this lifestyle is dangerous But I love it the rush is amazing Celebrate nightly and everyone rages I found how to cope with my anger I'm swimming in money Swimming in liquor my liver is muddy But it's all good I'm still sippin' this bubbly This shit is lovely, this shit ain't random, I didn't get lucky Made it right here 'cause I'm sick with it Cudi They all take the money for granted But don't want to work for it tell me now, isn't it funny? Nah Oh, it's just me, myself and I Solo \
    ride until I die 'Cause I got me for life (Got me for life, yeah) Oh I don't need a hand to hold Even when the night is cold I got that fire in my soul I don't need anything to get me through the night Except the beat that's in my heart Yeah, it's keeping me alive (Keeps me alive) I don't need anything to make me satisfied (You know) 'Cause the music fills me good and it gets me every time Like ba-ba-ba-ba-da-ba Ba-ba-ba-da-ba (Yee!) Ba-ba-ba-ba-da-ba Ba-ba-ba-da-ba Ba-ba-ba-ba-da-ba Ba-ba-ba-da-ba 'Cause the music fills me good and it gets me every time Yeah, lonely nights I laid awake Pray the Lord, my soul to take My heart's \
    become too cold to break Know I'm great but I'm broke as hell Having dreams that I'm folding cake All my life I've been told to wait But I'mma get it now, yeah it's no debate Yeah Oh, it's just me, myself and I Solo ride until I die 'Cause I got me for life (Got me for life, yeah) Oh I don't need a hand to hold Even when the night is cold I got that fire in my soul I don't need anything to get me through the night Except the beat that's in my heart Yeah, it's keeping me alive (Keeps me alive) I don't need anything to make me satisfied (You know) 'Cause the music fills me good and it gets me every time Like ba-ba-ba-ba-da-ba Ba-ba-ba\
    -da-ba Ba-ba-ba-ba-da-ba Ba-ba-ba-da-ba Ba-ba-ba-ba-da-ba Ba-ba-ba-da-ba 'Cause the music fills me good and it gets me every time",
    "No lyrics are available",
    "When the days are cold And the cards all fold And the saints we see Are all made of gold When your dreams all fail And the ones we hail Are the worst of all And the blood's run stale I wanna hide the truth I wanna shelter you But with the beast inside There's nowhere we can hide No matter what we breed We still are made of greed This is my kingdom come This is my kingdom come When you feel my heat Look into my eyes It's where my demons hide It's where my demons hide Don't get too close It's dark inside It's where my demons hide It's where my demons hide When the curtain's call Is the last of all When the lights fade out All the \
    sinners crawl So they dug your grave And the masquerade Will come calling out At the mess you made Find more lyrics at ※ Mojim.com Don't wanna let you down But I am hell bound Though this is all for you Don't wanna hide the truth No matter what we breed We still are made of greed This is my kingdom come This is my kingdom come When you feel my heat Look into my eyes It's where my demons hide It's where my demons hide Don't get too close It's dark inside It's where my demons hide It's where my demons hide They say it's what you make I say it's up to fate It's woven in my soul I need to let you go Your eyes, they shine so bright I \
    wanna save that light I can't escape this now Unless you show me how When you feel my heat Look into my eyes It's where my demons hide It's where my demons hide Don't get too close It's dark inside It's where my demons hide It's where my demons hide", 
    "About time for anyone telling you off for all your deeds No sign the roaring thunder stopped in cold to read No time Get mine and make no excuses waste of precious breath No time The sun shines on everyone, everyone love yourself to death So you gotta fire up, you gotta let go You'll never be loved till you've made your own You gotta face up, you gotta get yours You never know the top till you get too low A son of a stepfather A son of a I'm so sorry A son of a stepfather A son of a I'm so sorry No lies and no deceiving, that is what he loves I keep tryin' to conceive that death is from above No time I get by and make no excuses \
    waste of precious breath No time The sun shines on everyone, everyone love yourself to death So you gotta fire up, you gotta let go You'll never be loved till you've made your own You gotta face up, you gotta get yours You never know the top till you get too low A son of a stepfather A son of a I'm so sorry A son of a stepfather A son of a I'm so sorry Life isn't always what you think it'd be Turn your head for one second and the tables turn And I know, I know that I did you wrong But will you trust me when I say that I'll Make it up to you somehow, somehow So you gotta fire up, you gotta let go You'll never be loved till you've \
    made your own You gotta face up, you gotta get yours You never know the top till you get too low A son of a stepfather A son of a I'm so sorry A son of a stepfather A son of a I'm so sorry I'm so sorry I'm so sorry I'm so sorry A son of a",
    "You're so hypnotizing Could you be the devil? Could you be an angel? Your touch, magnetizing Feels like I am floating Leaves my body glowing They say, be afraid You're not like the others Futuristic lover Different DNA They don't understand you You're from a whole 'nother world A different dimension You open my eyes And I'm ready to go Lead me into the light Kiss me, ki-ki-kiss me Infect me with your lovin' Fill me with your poison Take me, ta-ta-take me Wanna be your victim Ready for abduction Boy, you're an alien Your touch, so foreign It's supernatural Extraterrestrial You're so supersonic Wanna feel your powers Stun me with \
    your laser Your kiss is cosmic Every move is magic You're from a whole 'nother world A different dimension You open my eyes And I'm ready to go Lead me into the light Kiss me, ki-ki-kiss me Infect me with your lovin' Fill me with your poison Take me, ta-ta-take me Wanna be your victim Ready for abduction Boy, you're an alien Your touch, so foreign It's supernatural Extraterrestrial This is transcendental On another level Boy, you're my lucky star I wanna walk on your wavelength And be there when you vibrate For you, I'll risk it all, all Kiss me, ki-ki-kiss me Infect me with your lovin' Fill me with your poison Take me, ta-ta-take \
    me Wanna be your victim Ready for abduction Boy, you're an alien Your touch, so foreign It's supernatural Extraterrestrial Extraterrestrial Extraterrestrial Boy, you're an alien Your touch, so foreign It's supernatural Extraterrestrial",
    "Breathing in the dark, lying on its side The ruins of the day painted with a scar And the more I straighten out, the less it wants to try The feelings start to rot, one wink at a time Oh-oh, forgiving who you are, for what you stand to gain Just know that if you hide, it doesn't go away When you get out of bed, don't end up stranded Horrified with each stone on the stage, my little dark age Picking through the cards, knowing what's nearby The carvings on the face say they find it hard And the engine's failed again, all limits of disguise The humor's not the same, coming from denial Oh-oh, I grieve in stereo, the stereo sounds \
    strange I know that if you hide, it doesn't go away If you get out of bed and find me standing all alone Open-eyed, burn the page, my little dark age I grieve in stereo, the stereo sounds strange You know that if it hides, it doesn't go away If I get out of bed, you'll see me standing all alone Horrified on the stage, my little dark age Giddy with delight, seeing what's to come The image of the dead, dead ends in my mind Policemen swear to God, love seeping from their guns I know my friends and I would probably turn and run If you get out of bed, come find us heading for the bridge Bring a stone, all the rage, my little dark age I \
    grieve in stereo, the stereo sounds strange I know that if you hide, it doesn't go away If you get out of bed and find me standing all alone Open-eyed, burn the page, my little dark age All alone, open-eyed, burn the page, my little dark age",
    "We clawed, we chained, our hearts in vain We jumped, never asking why We kissed, I fell under your spell A love no one could deny Don't you ever say I just walked away I will always want you I can't live a lie, running for my life I will always want you I came in like a wrecking ball I never hit so hard in love All I wanted was to break your walls All you ever did was wreck me Yeah, you, you wreck me I put you high up in the sky And now, you're not coming down It slowly turned, you let me burn And now, we're ashes on the ground Don't you ever say I just walked away I will always want you I can't live a lie, running for my life I \
    will always want you I came in like a wrecking ball I never hit so hard in love All I wanted was to break your walls All you ever did was wreck me I came in like a wrecking ball Yeah, I just closed my eyes and swung Left me crashing in a blazing fall All you ever did was wreck me Yeah, you, you wreck me I never meant to start a war I just wanted you to let me in And instead of using force I guess I should've let you win I never meant to start a war I just wanted you to let me in I guess I should've let you win Don't you ever say I just walked away I will always want you I came in like a wrecking ball I never hit so hard in love All \
    I wanted was to break your walls All you ever did was wreck me I came in like a wrecking ball Yeah, I just closed my eyes and swung Left me crashing in a blazing fall All you ever did was wreck me Yeah, you, you wreck me Yeah, you, you wreck me",
    "Cut my life into pieces This is my last resort Suffocation, no breathing Don't give a fuck if I cut my arm bleeding This is my last resort Cut my life into pieces I've reached my last resort Suffocation, no breathing Don't give a fuck if I cut my arm bleeding Do you even care if I die bleeding? Would it be wrong, would it be right If I took my life tonight? Chances are that I might Mutilation out of sight And I'm contemplating suicide 'Cause I'm losing my sight, losing my mind Wish somebody would tell me I'm fine Losing my sight, losing my mind Wish somebody would tell me I'm fine I never realized I was spread too thin 'Til it \
    was too late, and I was empty within Hungry, feeding on chaos and living in sin Downward spiral, where do I begin? It all started when I lost my mother No love for myself and no love for another Searching to find a love upon a higher level Finding nothing but questions and devils 'Cause I'm losing my sight, losing my mind Wish somebody would tell me I'm fine Losing my sight, losing my mind Wish somebody would tell me I'm fine Nothing's alright, nothing is fine I'm running and I'm crying I'm crying, I'm crying I'm crying, I'm crying I can't go on living this way Cut my life into pieces This is my last resort Suffocation, no breathing \
    Don't give a fuck if I cut my arm bleeding Would it be wrong, would it be right If I took my life tonight? Chances are that I might Mutilation out of sight And I'm contemplating suicide 'Cause I'm losing my sight, losing my mind Wish somebody would tell me I'm fine Losing my sight, losing my mind Wish somebody would tell me I'm fine Nothing's alright, nothing is fine I'm running and I'm crying I can't go on living this way Can't go on Living this way Nothing's alright",
    "Mm-mm-mm-mm-mm Mm-mm-mm-mm-mm Mm-ah-ah-ah Ah-ah-ah, ah-ah I'm wakin' up to ash and dust I wipe my brow and I sweat my rust I'm breathin' in the chemicals, ah I'm breakin' in and shapin' up Then checkin' out on the prison bus This is it, the apocalypse, whoa I'm waking up (oh), I feel it in my bones Enough to make my system blow Welcome to the new age (oh), to the new age (oh) Welcome to the new age (oh-oh), to the new age Whoa, oh, whoa, I'm radioactive, radioactive Whoa, oh, whoa, I'm radioactive, radioactive La-la, la-la, la-la, la-la, la-la, oh-oh-oh La-la, la-la, la-la, la-la, la-la, whoa, oh, oh I'm breakin' in (breakin' in), \
    shapin' up (shapin' up) Checkin' out on the prison bus (ah) This is it (this is it, oh), the apocalypse, whoa I'm wakin' up (ah), I feel it in my bones Enough to make my system blow Welcome to the new age (oh), to the new age (oh) Welcome to the new age (oh-oh), to the new age Whoa, oh, whoa, I'm radioactive, radioactive Whoa, oh, whoa, I'm radioactive, radioactive All systems go, sun hasn't died Deep in my bones, straight from inside Ooh-ooh, ooh-ooh, ooh-ooh, ooh-ooh I'm wakin' up Welcome to the new age (all systems go), to the new age Welcome to the new age (sun hasn't died) I'm wakin' up I feel it in my bones Enough to make my \
    system blow Welcome to the new age (oh), to the new age (oh) Welcome to the new age (oh-oh), to the new age Whoa, oh, whoa, I'm radioactive, radioactive Whoa, oh, whoa, I'm radioactive, radioactive",
    "Rumbling, Rumbling, it's coming! Rumbling, Rumbling! Beware! Coming for you! All I ever wanted to do was do right things I never wanted to be the king, I swear All I ever wanted to do was save your life I never wanted to grab a knife, I swear I'm tearless, I'm fearless I'm burning, I'm burning You tell me what have I missed? Still wandering in the deep mist If I lose it all, slip and fall I will never look away If I lose it all, lose it all, lose it all If I lose it all outside the wall Live to die another day I don't want anything, I'm just here to... Beware! All I ever wanted to do was know what's out there? I refused to lose \
    without a fight, oh, oh-yeah Oh-oh, ooh-oh-oh We're just too young, ignorant and innocent Like kids stay up all night in a tent, oh yeah How do you see me? Oh yeah Am I who I used to be? Beware! Nobody knows what's inside of me Nobody knows what's inside of me Nobody knows what's inside of me Ah If I lose it all, slip and fall Will you laugh at me? If I lose it all, lose it all Ah-ah-ah, ah-ah If I lose it all, slip and fall I will never look away If I lose it all, lose it all, lose it all If I lose it all outside the wall Live to die another day I don't want anything, I'm just here to... Beware! Rumbling, Rumbling, it's coming! \
    Rumbling, Rumbling! Coming for you! Rumbling, Rumbling, it's coming! Rumbling, Rumbling!",
    "All smiles, I know what it takes to fool this town I'll do it 'til the sun goes down And all through the nighttime Oh, yeah Oh, yeah, I'll tell you what you wanna hear Leave my sunglasses on while I shed a tear It's never the right time Yeah, yeah I put my armor on, show you how strong I am I put my armor on, I'll show you that I am I'm unstoppable I'm a Porsche with no brakes I'm invincible Yeah, I win every single game I'm so powerful I don't need batteries to play I'm so confident Yeah, I'm unstoppable today Unstoppable today Unstoppable today Unstoppable today I'm unstoppable today Break down, only alone I will cry out loud \
    You'll never see what's hiding out Hiding out deep down Yeah, yeah I know, I've heard that to let your feelings show Is the only way to make friendships grow But I'm too afraid now Yeah, yeah I put my armor on, show you how strong I am I put my armor on, I'll show you that I am I'm unstoppable I'm a Porsche with no brakes I'm invincible Yeah, I win every single game I'm so powerful I don't need batteries to play I'm so confident Yeah, I'm unstoppable today Unstoppable today Unstoppable today Unstoppable today I'm unstoppable today Unstoppable today Unstoppable today Unstoppable today I'm unstoppable today I put my armor on, show \
    you how strong I am I put my armor on, I'll show you that I am I'm unstoppable I'm a Porsche with no brakes I'm invincible Yeah, I win every single game I'm so powerful I don't need batteries to play I'm so confident Yeah, I'm unstoppable today Unstoppable today Unstoppable today Unstoppable today I'm unstoppable today Unstoppable today Unstoppable today Unstoppable today I'm unstoppable today",
    "Wake up (wake up) Grab a brush and put a little make-up Hide the scars to fade away the shake-up (hide the scars to fade away the-) Why'd you leave the keys upon the table? Here you go create another fable, you wanted to Grab a brush and put a little make-up, you wanted to Hide the scars to fade away the shake-up, you wanted to Why'd you leave the keys upon the table? You wanted to I don't think you trust In my self-righteous suicide I cry when angels deserve to die Wake up (wake up) Grab a brush and put a little make-up Hide the scars to fade away the (hide the scars to fade away the shake-up) Why'd you leave the keys upon the \
    table? Here you go create another fable, you wanted to Grab a brush and put a little make-up, you wanted to Hide the scars to fade away the shake-up, you wanted to Why'd you leave the keys upon the table? You wanted to I don't think you trust In my self-righteous suicide I cry when angels deserve to die In my self-righteous suicide I cry when angels deserve to die Father (father) Father (father) Father (father) Father (father) Father, into your hands I commend my spirit Father, into your hands Why have you forsaken me? In your eyes forsaken me In your thoughts forsaken me In your heart forsaken me, oh Trust in my self-righteous \
    suicide I cry when angels deserve to die In my self-righteous suicide I cry when angels deserve to die",
    "I'm not the same as yesterday Oh, it's hard to explain How things have changed But I'm not the same as before And I know there's so much more ahead I can barely believe that I'm here And I won't surrender quietly Step up and watch me go Break down, ya really want it? Wanna make a scene? Show me what ya mean Let's get it started Let me see whatcha got Can ya take it up a knotch? Don't think you got it Can't handle the pressure? Get, off, stop talkin' about it Gotta make this count, let's go When we move We camouflage ourselves We stand in the shadows waiting We live for this and nothing more We are what You created I can feel the \
    storm The winds have changed Ooh...'Cause we're worlds a part But just the same But we won't leave the way that we came And I know there's so much more ahead I can barely believe that we're here We won't surrender quietly Step up and watch it go Break down, ya really want it? Wanna make a scene? Show me what ya mean Let's get it started Let me see whatcha got Can ya take it up a knotch? Don't think you got it Can't handle the pressure? Get, off, stop talkin' about it Gotta make this count, let's go When we move We camouflage ourselves We stand in the shadows waiting We live for this and nothing more We are what You created Are you \
    ready? Are ya ready? Are ya ready for me? Are you ready? Are ya ready? Are ya ready to see? When we move We camouflage ourselves We stand in the shadows waiting We live for this and nothing more We are what You created",
    "It's a truth that in love and war World's collide and hearts get broken I want to live like I know I'm dying Take up my cross, not be afraid Is it true what they say, that words are weapons? And if it is, then everybody best stop steppin 'Cause I got ten in my pocket that'll bend ya locket I'm tired of all these rockers saying come with me Wait, it's just about to break, it's more than I can take Everything's about to change I feel it in my veins, it's not going away Everything's about to change It creeps in like a thief in the night Without a sign, without a warning But we are ready and prepared to fight Raise up your swords, \
    don't be afraid Is it true what they say, that words are weapons? And if it is, then everybody best stop steppin' 'Cause I got ten in my pocket that'll bend ya locket I'm tired of all these rockers sayin' come with me Wait, it's just about to break, it's more than I can take Everything's about to change I feel it in my veins, it's not going away Everything's about to change This is a warning, like it or not I break down, like a record spinning Gotta get up, so back off This is a warning, like it or not I'm tired of listenin', I'm warning you don't try to get up There's a war going on inside of me tonight (don't be afraid) There's a \
    war going on inside of me tonight (don't be afraid) Wait, it's just about to break, it's more than I can take Everything's about to change I feel it in my veins, it's not going away Everything's about to change It's just about to break, it's more than I can take Everything's about to change I feel it in my veins, it's not going away Everything's about to change",
    "Every time we lie awake After every hit we take Every feeling that I get But I haven't missed you yet Every roommate kept awake By every sigh and scream we make All the feelings that I get But I still don't miss you yet Only when I stop to think about it I hate everything about you Why do I love you? I hate everything about you Why do I love you? Every time we lie awake After every hit we take Every feeling that I get But I haven't missed you yet Only when I stop to think about it I hate everything about you Why do I love you? I hate everything about you Why do I love you? Only when I stop to think About you, I know Only when you \
    stop to think About me, do you know? I hate everything about you Why do I love you? You hate everything about me Why do you love me? I hate You hate I hate You love me I hate everything about you Why do I love you?",
    "Buddy, you're a boy, make a big noise Playing in the street, gonna be a big man someday You got mud on your face, you big disgrace Kicking your can all over the place Singing We will, we will rock you We will, we will rock you Buddy, you're a young man, hard man Shouting in the street, gonna take on the world someday You got blood on your face, you big disgrace Waving your banner all over the place We will, we will rock you Sing it! We will, we will rock you Buddy, you're an old man, poor man Pleading with your eyes, gonna make you some peace someday You got mud on your face, you big disgrace Somebody better put you back into your \
    place We will, we will rock you Sing it! We will, we will rock you Everybody We will, we will rock you We will, we will rock you",
    "No lyrics are available",
    "(It starts with one) One thing, I don't know why It doesn't even matter how hard you try Keep that in mind, I designed this rhyme To explain in due time (all I know) Time is a valuable thing Watch it fly by as the pendulum swings Watch it count down to the end of the day The clock ticks life away, it's so unreal (it's so unreal) You didn't look out below Watch the time go right out the window Trying to hold on, to didn't even know I wasted it all just to watch you go (watch you go) I kept everything inside And even though I tried, it all fell apart What it meant to me will eventually Be a memory of a time when I tried so hard and \
    got so far But in the end, it doesn't even matter I had to fall to lose it all But in the end, it doesn't even matter One thing, I don't know why It doesn't even matter how hard you try Keep that in mind I designed this rhyme To remind myself how I tried so hard (I tried so hard) In spite of the way you were mocking me Acting like I was part of your property Remembering all the times you fought with me I'm surprised it got so far (got so far) Things aren't the way they were before You wouldn't even recognize me anymore Not that you knew me back then But it all comes back to me (in the end) You kept everything inside And even though \
    I tried, it all fell apart What it meant to me will eventually Be a memory of a time when I tried so hard and got so far But in the end, it doesn't even matter I had to fall to lose it all But in the end, it doesn't even matter I've put my trust in you Pushed as far as I can go For all this There's only one thing you should know I've put my trust in you Pushed as far as I can go For all this There's only one thing you should know I tried so hard and got so far But in the end, it doesn't even matter I had to fall to lose it all But in the end, it doesn't even matter",
    "Conversion, software version 7.0 Looking at life through the eyes of a tire hub Eating seeds as a pastime activity The toxicity of our city, of our city You, what do you own the world? How do you own disorder, disorder? Now, somewhere between the sacred silence Sacred silence and sleep Somewhere Between the sacred silence and sleep Disorder, disorder, disorder More wood for their fires, loud neighbors Flashlight reveries caught in the headlights of a truck Eating seeds as a pastime activity The toxicity of our city, of our city You, what do you own the world? How do you own disorder, disorder? Now, somewhere between the sacred \
    silence Sacred silence and sleep Somewhere Between the sacred silence and sleep Disorder, disorder, disorder You, what do you own the world? How do you own disorder? Now, somewhere between the sacred silence Sacred silence and sleep Somewhere Between the sacred silence and sleep Disorder, disorder, disorder When I became the Sun I shone life into the man's hearts When I became the Sun I shone life into the man's hearts",
    "I wish I found some better sounds no one's ever heard I wish I had a better voice that sang some better words I wish I found some chords in an order that is new I wish I didn't have to rhyme every time I sang I was told, when I get older, all my fears would shrink But now I'm insecure, and I care what people think My name's Blurryface and I care what you think My name's Blurryface and I care what you think My name's Blurryface and I care what you think My name's Blurryface and I care what you think Wish we could turn back time to the good old days When our momma sang us to sleep, but now we're stressed out Wish we could turn back \
    time to the good old days When our momma sang us to sleep, but now we're stressed out Sometimes a certain smell will take me back to when I was young How come I'm never able to identify where it's comin' from? I'd make a candle out of it, if I ever found it Try to sell it, never sell out of it, I'd probably only sell one (one, one) It'd be to my brother, 'cause we have the same nose Same clothes, homegrown, a stone's throw from a creek we used to roam (roam, roam) But it would remind us of when nothing really mattered Out of student loans and treehouse homes, we all would take the latter My name's Blurryface and I care what you think \
    My name's Blurryface and I care what you think Yeah, we used to play pretend, give each other different names We would build a rocket ship, and we'd fly it far away Yeah, we used to play pretend, give each other different names We would build a rocket ship, and we'd fly it far away Wish we could turn back time to the good old days When our momma sang us to sleep (Yeah, we used to play pretend, give each other different names) Wish we could turn back time to the good old days (We would build a rocket ship, and we'd fly it far away) When our momma sang us to sleep (Yeah, we used to play pretend, give each other different names) Wish we \
    could turn back time to the good old days (We would build a rocket ship, and we'd fly it far away) When our momma sang us to sleep, but now we're stressed out (Yeah, we used to play pretend, give each other different names) Wish we could turn back time to the good old days (We would build a rocket ship, and we'd fly it far away) When our momma sang us to sleep, but now we're stressed out We're stressed out",
    "My legs are dangling off the edge The bottom of the bottle is my only friend I think I'll slit my wrists again and I'm Gone, gone, gone, gone My legs are dangling off the edge A stomach full of pills didn't work again I'll put a bullet in my head and I'm Gone, gone, gone, gone Gone to far yea I'm gone again It's gone on to long, tell you how it ends I'm sitting on the edge with my two best friends Ones a bottle of pills and ones a bottle of gin I'm twenty stories up, yea up at the top I've polished off this bottle now it's pushin' me off Asphalt to me, has never looked so soft I bet my momma found my letter, now she's calling the \
    cops I've gotta take this opportunity before I miss it 'Cause now I hear the sirens and there off in the distance Believe me when I tell you that I've been persistent 'Cause I'm more scarred, more scarred then my wrist is I've been trying to long with too dull of a knife But tonight I made sure, that I sharpened it twice I've never bought a suit before in my life But when you go to meet god you know you wanna look nice So if I survive then I'll see you tomorrow Yea I'll see you tomorrow My legs are dangling off the edge The bottom of the bottle is my only friend I think I'll slit my wrists again and I'm Gone, gone, gone, gone My \
    legs are dangling off the edge A stomach full of pills didn't work again I'll put a bullet in my head and I'm Gone, gone, gone, gone We hit the sky, there goes the light No more sun, why's it always night When you can't sleep, well you can't dream When you can't dream well, what's life mean? We feel a little pity but don't empathize The old are getting old, watch a young man die A mother and her son, and someone you know Smiles at each other and realize you don't You don't know what happened to that kid you raised What happened to that father, who swore he'd stay I didn't know 'cause you didn't say Now momma feels guilt, yea momma \
    feels pain When you were young, you never thought you'd die Found that you could but too scared to try Looked in the mirror and you said goodbye Climbed to the roof to see you if could fly So if I survive then I'll see you tomorrow Yea, I'll see you tomorrow My legs are dangling off the edge The bottom of the bottle is my only friend I think I'll slit my wrists again and I'm Gone, gone, gone, gone My legs are dangling off the edge A stomach full of pills didn't work again I'll put a bullet in my head and I'm Gone, gone, gone, gone I wish that I could fly Way up in the sky Like a bird so high Oh, I might just try I wish that I could \
    fly Way up in the sky Like a bird so high Oh, I might just try Oh, I might just try",
    "As the moon ascends The wolves come out to see the end They hide from view and wait To watch the ghost inside you come awake And when the shots go off you'll hear them call My heart is racing just to see it all To watch it crawl out of you changing shape To take all your breath and watch it come awake From the flames of the fire I feel you crawl into my bed Throwing shapes at the sky I watch you climb into me With your knees open On display you taunt the beast again 'Cause when you move and shake The thing inside you comes awake As you dance against the breathing wall My claws are out I want to feel it all Feel it crawl inside you \
    changing shape Take out your breath and feel you come awake From the flames of the fire I feel you crawl into my bed Throiwng shapes at the sky I watch you climb into me Say something, pray for something Say something, pray or something Say something, pray for something Say something, pray or something From the flames of the fire I watch you crawl into me From the flames of the fire I feel you crawl into my bed Throwing shapes at the sky I watch you crawl into me Say something Pray for something Say something Pray for something Say",
]; 

var musicsNamesArray = [
    "Hollywood Undead - Believe",
    "Hollywood Undead - Lion",
    "Evanescence - My Last Breath",
    "2CELLOS - Thunderstruck",
    "The Chordettes - Mr. Sandman",
    "Metallica - Sad but True",
    "Adele - Set Fire to the Rain",
    "Bring Me The Horizon - Can You Feel My Heart",
    "Linkin Park - Castle Of Glass",
    "Coldrain - We're Not Alone",
    "Thousand Foot Krutch - Courtesy Call",
    "Dr. Dre feat. Eminem & Xzibit - What's The Difference",
    "Eminem & Linkin Park - Acid Rain",
    "Eminem - Lose Yourself (Instrumental)",
    "Eminem - Rap God",
    "Evanescence - Bring Me To Life",
    "G-Eazy x Bebe Rexha - Me, Myself & I",
    "Hunter X Hunter - Opening 1",
    "Imagine Dragons - Demons",
    "Imagine Dragons - I'm So Sorry",
    "Katy Perry - ET",
    "MGMT - Little Dark Age",
    "Miley Cyrus - Wrecking Ball",
    "Papa Roach - Last Resort",
    "Radioactive - Lindsey Stirling and Pentatonix",
    "AOT opening - The Rumbling",
    "Sia - Unstoppable",
    "System Of A Down - Chop Suey!",
    "Thousand Foot Krutch - E for Extinction",
    "Thousand Foot Krutch - War of Change",
    "Three Days Grace - I Hate Everything About You",
    "Queen - We Will Rock You",
    "Coolio - Gangsta's Paradise (Instrumental)",
    "Linkin Park - In the End (Cover Jung Youth & Fleurie)",
    "System Of A Down - Toxicity",
    "Twenty One Pilots - Stressed Out",
    "Hollywood Undead - Bullet",
    "Crosses - Bitches Brew"
];


var musicArray = [
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2Fy2meta.com%20-%20Hollywood%20Undead%20-%20_Believe_%20(Official%20Lyric%20Video)%20(320%20kbps).mp3?alt=media&token=2633b953-318d-4ac1-a9c5-cbc39ca8f823",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2Fy2meta.com%20-%20Hollywood%20Undead%20-%20_Lion_%20(Official%20Lyric%20Video)%20(320%20kbps).mp3?alt=media&token=9581d28a-3863-4053-b551-0b758991d35b",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2F10%20-%20my%20last%20breath.mp3?alt=media&token=b461e6a9-ef1f-41b3-b984-34b9257dab43",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2F2CELLOS%20-%20Thunderstruck%20%5BOFFICIAL%20VIDEO%5D.mp3?alt=media&token=8ec945e0-a24f-40ae-96ae-8ea0d52d3cb7",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2F331690807662.mp3?alt=media&token=91bbef00-2075-40a8-a7d5-0ee36dfb3b08",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2F80fa_c566.mp3?alt=media&token=7165b7af-e72c-4469-bac9-05ca1f3b882a",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FAdele%20-%20Set%20Fire%20to%20the%20Rain%20Lyrics.mp3?alt=media&token=16e51672-4d05-4cda-93ba-7cbd36de5f6a",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FBring%20Me%20The%20Horizon%20-%20Can%20You%20Feel%20My%20Heart%20(128%20%20kbps)%20(s.shabakngy.com).mp3?alt=media&token=8a556e93-cd50-4fd0-8ecd-bd58924dfb4b",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FCastle%20Of%20Glass%20(OST%20Medal%20of%20Honor_%20Warfighter)-Linkin%20Park.mp3?alt=media&token=79b82854-24ac-4e3e-b25a-386b65e82a47",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FColdrain_-_We_re_not_alone_Rainbow_Nisha_Rokubou_no_Shichinin_OST_Opening_(mp3.pm).mp3?alt=media&token=09252cec-7155-4c8b-850b-4e4f7fcebc21",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FCourtesy%20Call%20-%20Thousand%20Foot%20Krutch.mp3?alt=media&token=075631f1-8869-4adc-9823-dc395462b82f",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FDr._Dre_feat._Eminem_Xzibit_-_What_s_The_Difference_(ColdMP3.com).mp3?alt=media&token=2213fe30-044e-4dab-b6f7-b93ca93b9ae0",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FEminem%20%26%20Linkin%20Park%20-%20Acid%20Rain%20%5BAfter%20Collision%202%5D.mp3?alt=media&token=4e7ee3d2-7444-49f8-85d7-82c1d2415f16",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FEminem%20-%20Lose%20Yourself%20_Instrumental_%20HQ.mp3?alt=media&token=e43083ee-7983-41ad-998f-c4dcf53b8667",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FEminem%20-%20Rap%20God%20HD.mp3?alt=media&token=d3a9b00e-fe2b-46b9-b69c-7668e62937d1",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FEvanescence%20-%20Bring%20Me%20To%20Life%20(Official%20Music%20Video).mp3?alt=media&token=ee21173d-2b16-44d8-bf08-55f58ec380a9",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FG-Eazy%20x%20Bebe%20Rexha%20-%20Me%2C%20Myself%20%26%20I%20(Lyrics%20Video).mp3?alt=media&token=1fdf3928-24a1-4f0b-98da-e3ffa00ea31b",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FHunter%20X%20Hunter%20-%20Opening%201%20-%20Full.mp3?alt=media&token=28eec6b5-64a8-4a0b-98dd-56593ae4a121",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FImagine%20Dragons%20-%20Demons%20(Official).mp3?alt=media&token=3aba6215-3f58-4a05-ad36-bd6f8c6708ac",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FImagine%20Dragons%20-%20Im%20So%20Sorry%20(Lyrics).mp3?alt=media&token=0d57510d-3e5f-4a2b-8140-31da0f322fba",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FKaty%20Perry%20-%20ET%20(Metal%20Cover%20by%20Jotun%20Studio).mp3?alt=media&token=299a2288-ba2b-4475-a68b-c42f7489543d",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FMGMT_-_Little_Dark_Age.mp3?alt=media&token=e0823ede-faed-4875-b6b5-402c70669130",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FMiley%20Cyrus%20-%20Wrecking%20Ball.mp3?alt=media&token=86cbcbc2-6596-4b4d-8772-934b4615d9f8",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FPapa%20Roach%20%20Last%20Resort%20lyrics.mp3?alt=media&token=1528790c-5940-41ad-8cc9-09b2be822d07",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FRadioactive%20-%20Lindsey%20Stirling%20and%20Pentatonix%20(Imagine%20Dragons%20Cover).mp3?alt=media&token=db556957-f5d5-43df-ad7c-d9b482804ed3",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FSIM-The-Rumbling-(HipHopKit.com).mp3?alt=media&token=c7355a44-67b9-4f57-9297-e9893021e1c1",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FSia%20-%20Unstoppable%20(Lyrics).mp3?alt=media&token=eaf1b168-e9c2-40ad-bcdb-4ad4096df867",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FSystem%20Of%20A%20Down%20-%20Chop%20Suey!.mp3?alt=media&token=c44c3ae6-d9c4-492a-8078-8499047b2d8e",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FThousand%20Foot%20Krutch%20-%20E%20for%20Extinction%20%5BLYRICS%5D.mp3?alt=media&token=fecaeb58-df72-46f7-81ec-855ef78b37dd",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FThousand%20Foot%20Krutch_%20War%20of%20Change%20(Official%20Music%20Video)%20(128%20%20kbps)%20(s.shabakngy.com).mp3?alt=media&token=ca77cc88-6166-4570-9615-6388d58e5cb3",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FThree%20Days%20Grace%20-%20I%20Hate%20Everything%20About%20You%20(Official%20Video).mp3?alt=media&token=4b11d94e-644b-4afe-88a7-4d9d66692657",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2FWe%20will%20rock%20you%20-%20Queen-.mp3?alt=media&token=a3a814fa-ba6e-41d1-9b6a-b5e2c496276d",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2Fgangsta39s-paradise-lofi-fruits-music-tiktok-remix-extended_456303168.mp3?alt=media&token=78124471-1902-4a1f-b6ac-8198936d4317",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2Fin-the-end-linkin-park-cinematic-cover-feat-jung-youth-fleurie-produced-by-tommee-profitt.mp3?alt=media&token=c2bd826c-4404-4442-a944-e657508f7bfd",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2Fsystem%20of%20a%20down%20-%20toxicity.mp3?alt=media&token=b8ea618c-ef29-4dfd-af19-aa1750fb35f6",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2Ftwenty%20one%20pilots%20Stressed%20Out%20%5BOFFICIAL%20VIDEO%5D.mp3?alt=media&token=b5959c84-78a5-4551-b1db-bb2a05a64a43",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2Fy2meta.com%20-%20Hollywood%20Undead%20-%20Bullet%20(Lyric%20Video)%20(320%20kbps).mp3?alt=media&token=48679854-6d78-4dab-93e7-f39563be31c2",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkMusics%2F%E2%80%A0%E2%80%A0%E2%80%A0%20(Crosses)%20-%20Bitches%20Brew%20(Official%20Music%20Video).mp3?alt=media&token=f65d8471-f99a-40e1-93c0-96521f4d06d6",
];
var videosArray = [
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo15.mp4?alt=media&token=7de75a8d-a329-43b7-8f1f-d468e1e2bcab",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo1.mp4?alt=media&token=2e5b3a8d-9818-4655-9acd-945193908e4e",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo3.mp4?alt=media&token=e46d11a5-d9c5-4a37-a8b4-3437ee322654",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo5.mp4?alt=media&token=70de0046-e4a1-48c2-b9af-5c5591f84239",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo6.mp4?alt=media&token=3e03641c-3217-41d1-8510-4e1471a1c52d",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo7.mp4?alt=media&token=b619e371-e884-484b-9c12-120f8c3643bc",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo8.mp4?alt=media&token=bcb36dac-fe74-47eb-8860-63ca36a259fd",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo9.mp4?alt=media&token=8a2788b3-96ec-42da-8ed8-9ee6ca40a1a7",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo10.mp4?alt=media&token=5c06e157-1137-49d5-88b6-edaeefc580f4",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo11.mp4?alt=media&token=ecd7fbb8-d667-4b84-92c8-c8c26702d537",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo12.mp4?alt=media&token=9a15a20c-7f2d-4f84-939e-1194d73b980d",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo13.mp4?alt=media&token=d1701f06-e29f-405b-8210-4c92142c330e",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo14.mp4?alt=media&token=5aed1221-43b1-4e16-8810-aa021ab6ff91",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo16.mp4?alt=media&token=9b2af4d3-d51c-48a8-9f3f-43462b7f7baf",
    "https://firebasestorage.googleapis.com/v0/b/ibulk-452a7.appspot.com/o/iBulkVideos%2FVideo17.mp4?alt=media&token=58d70416-348a-453c-913b-5ef4d3eb3e97",
];
var quotesArray = [
    "Strength does not come from physical capacity. It comes from an indomitable will. -Mahatma Gandhi",
    "Success usually comes to those who are too busy to be looking for it. -Henry David Thoreau",
    "If you want something you've never had, you must be willing to do something you've never done. -Thomas Jefferson",
    "The body achieves what the mind believes.",
    "Once you are exercising regularly, the hardest thing is to stop it. -Erin Gray",
    "If you don't make time for exercise, you'll probably have to make time for illness. -Robin Sharma",
    "The best way to predict the future is to create it. -Abraham Lincoln",
    "Rome wasn't built in a day, but they worked on it every single day.",
    "All progress takes place outside the comfort zone. -Michael John Bobak",
    "What seems impossible today will one day become your warm-up.",
    "The only bad workout is the one that didn't happen.",
    "Don't stop when you're tired, stop when you're done.",
    "Strength does not come from the body. It comes from the will.",
    "Your body is a reflection of your lifestyle.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Excuses don't burn calories.",
    "Sweat is just fat crying.",
    "Fitness is not about being better than someone else; it's about being better than you used to be.",
    "Your only limit is you.",
    "The only workout you'll regret is the one that didn't happen.",
    "Fall in love with taking care of yourself: mind, body, and spirit.",
    "Success is the sum of small efforts repeated day in and day out.",
    "Make yourself a priority. At the end of the day, you're your longest commitment.",
    "The body achieves what the mind believes.",
    "It's not about having time; it's about making time.",
    "The difference between a goal and a dream is a deadline.",
    "Strive for progress, not perfection.",
    "The only way to define your limits is by going beyond them.",
    "Your health is an investment, not an expense.",
    "You are one workout away from a good mood.",
    "Fitness is not just about the body. It's also about the mind and the soul.",
    "The greatest wealth is health.",
    "Challenges are what make life interesting; overcoming them is what makes life meaningful.",
    "Make today so awesome that yesterday gets jealous.",
    "Your body can stand almost anything. It's your mind that you have to convince.",
    "The only way to do great work is to love what you do.",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Work hard in silence; let success make the noise.",
    "You don't have to be extreme, just consistent."
];