var bodyQuadracepsOne = document.createElement("img");
var bodyQuadracepsTwo = document.createElement("img");
var bodyAbdominis = document.createElement("img");
var bodyChestOne = document.createElement("img");
var bodyChestTwo = document.createElement("img");
var bodyBicepsOne = document.createElement("img");
var bodyBicepsTwo = document.createElement("img");
var bodyCalvesOne = document.createElement("img");
var bodyCalvesTwo = document.createElement("img");
var bodyDeltoidsOne = document.createElement("img");
var bodyDeltoidsTwo = document.createElement("img");
var bodyForearmsOne = document.createElement("img");
var bodyForearmsTwo = document.createElement("img");
var bodyObliquesOne = document.createElement("img");
var bodyObliquesTwo = document.createElement("img");
var bodyObliquesThree = document.createElement("img");
var bodyObliquesFour = document.createElement("img");
var bodyTrapsOne = document.createElement("img");
var bodyTrapsTwo = document.createElement("img");

var bodyHamstringsOne = document.createElement("img");
var bodyHamstringsTwo = document.createElement("img");
var bodyGlutes = document.createElement("img");
var bodyLowerBack = document.createElement("img");
var bodyLowerTraps = document.createElement("img");
var bodyTricepsOne= document.createElement("img");
var bodyTricepsTwo = document.createElement("img");
var bodyBackCalvesOne = document.createElement("img");
var bodyBackCalvesTwo= document.createElement("img");
var bodyBackDeltoidsOne = document.createElement("img");
var bodyBackDeltoidsTwo = document.createElement("img");
var bodyBackForearmsOne = document.createElement("img");
var bodyBackForearmsTwo = document.createElement("img");
var bodyBackTraps = document.createElement("img");
var bodyBackLatsOne = document.createElement("img");
var bodyBackLatsTwo = document.createElement("img");
var bodyBackLatsThree = document.createElement("img");
var bodyBackLatsFour = document.createElement("img");

var quadracepsPicture = document.createElement("img");
var abdominisPicture = document.createElement("img");
var chestPicture = document.createElement("img");
var calvesPicture = document.createElement("img");
var deltoidsPicture = document.createElement("img");
var bicepsPicture = document.createElement("img");
var forearmsPicture = document.createElement("img");
var trapsPicture = document.createElement("img");
var obliquesPicture = document.createElement("img");

var hamstringsPicture = document.createElement("img");
var glutesPicture = document.createElement("img");
var lowerBackPicture = document.createElement("img");
var tricepsPicture = document.createElement("img");
var lowerTrapsPicture = document.createElement("img");
var latsPicture = document.createElement("img");

bodyQuadracepsOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyQuadraceps.png";
bodyQuadracepsTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyQuadraceps.png";
bodyAbdominis.src = "ProjectMedia/ProjectPictures/MaleBody/bodyAbdominis.png";
bodyChestOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyChest.png";
bodyChestTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyChest.png";
bodyBicepsOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBiceps.png";
bodyBicepsTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBiceps.png";
bodyCalvesOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyCalves.png";
bodyCalvesTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyCalves.png";
bodyDeltoidsOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyDeltoids.png";
bodyDeltoidsTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyDeltoids.png";
bodyForearmsOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyForearms.png";
bodyForearmsTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyForearms.png";
bodyTrapsOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyTraps.png";
bodyTrapsTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyTraps.png";
bodyObliquesOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyObliques.png";
bodyObliquesTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyObliques.png";
bodyObliquesThree.src = "ProjectMedia/ProjectPictures/MaleBody/bodyObliques.png";
bodyObliquesFour.src = "ProjectMedia/ProjectPictures/MaleBody/bodyObliques.png";

bodyHamstringsOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyHamstrings.png";
bodyHamstringsTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyHamstrings.png";
bodyGlutes.src = "ProjectMedia/ProjectPictures/MaleBody/bodyGlutes.png";
bodyLowerBack.src = "ProjectMedia/ProjectPictures/MaleBody/bodyLowerBack.png";
bodyLowerTraps.src = "ProjectMedia/ProjectPictures/MaleBody/bodyLowerTraps.png";
bodyTricepsOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyTriceps.png";
bodyTricepsTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyTriceps.png";
bodyBackCalvesOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBackCalves.png";
bodyBackCalvesTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBackCalves.png";
bodyBackDeltoidsOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBackDeltoids.png";
bodyBackDeltoidsTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBackDeltoids.png";
bodyBackForearmsOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBackForearms.png";
bodyBackForearmsTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBackForearms.png";
bodyBackTraps.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBackTraps.png";
bodyBackLatsOne.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBackLats.png";
bodyBackLatsTwo.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBackLats.png";
bodyBackLatsThree.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBackLats.png";
bodyBackLatsFour.src = "ProjectMedia/ProjectPictures/MaleBody/bodyBackLats.png";

quadracepsPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/quadriceps.jpg";
abdominisPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/abdominis.jpg";
chestPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/chest.jpg";
calvesPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/calves.jpg";
deltoidsPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/deltoids.jpg";
bicepsPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/biceps.jpg";
forearmsPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/forearms.jpg";
trapsPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/trapezius.jpg";
obliquesPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/obliques.jpg";
hamstringsPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/hamstring.jpg";
glutesPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/glutes.jpg";
lowerBackPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/lowerBack.jpg";
lowerTrapsPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/lowerTraps.jpg";
tricepsPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/triceps.jpg";
latsPicture.src = "ProjectMedia/ProjectPictures/AnotomyPictures/lats.jpg";

var frontMusclesParagraphs = [
    "The quadriceps muscle, commonly referred to as the quads, is a group of four muscles located on the front of the thigh. These muscles work together to extend the knee and straighten the leg. The four muscles that make up the quadriceps are: Rectus Femoris: This is the only quadriceps muscle that crosses both the hip and knee joints. It originates from the front of the hip bone (iliac crest) and inserts into the patella (kneecap) and then continues as the patellar tendon to attach to the tibia (shinbone).     Vastus Lateralis: This muscle is on the outer side of the thigh. It originates from the femur (thigh bone) and attaches to the patella via the quadriceps tendon. Vastus Medialis: Situated on the inner side of the thigh, this muscle also originates from the femur and attaches to the patella through the quadriceps tendon. It plays a significant role in stabilizing the patella during movements like walking and running. Vastus Intermedius: This muscle lies beneath the rectus femoris and is located deep within the thigh. It originates from the front of the femur and also attaches to the patella through the quadriceps tendon. Together, the quadriceps muscles are vital for various movements such as walking, running, jumping, and climbing stairs. They also play a crucial role in maintaining proper posture and stability around the knee joint. Strengthening exercises for the quadriceps are often prescribed in physical therapy and rehabilitation programs for knee injuries or after knee surgeries.",
    "The quadriceps muscle, commonly referred to as the quads, is a group of four muscles located on the front of the thigh. These muscles work together to extend the knee and straighten the leg. The four muscles that make up the quadriceps are: Rectus Femoris: This is the only quadriceps muscle that crosses both the hip and knee joints. It originates from the front of the hip bone (iliac crest) and inserts into the patella (kneecap) and then continues as the patellar tendon to attach to the tibia (shinbone).     Vastus Lateralis: This muscle is on the outer side of the thigh. It originates from the femur (thigh bone) and attaches to the patella via the quadriceps tendon. Vastus Medialis: Situated on the inner side of the thigh, this muscle also originates from the femur and attaches to the patella through the quadriceps tendon. It plays a significant role in stabilizing the patella during movements like walking and running. Vastus Intermedius: This muscle lies beneath the rectus femoris and is located deep within the thigh. It originates from the front of the femur and also attaches to the patella through the quadriceps tendon. Together, the quadriceps muscles are vital for various movements such as walking, running, jumping, and climbing stairs. They also play a crucial role in maintaining proper posture and stability around the knee joint. Strengthening exercises for the quadriceps are often prescribed in physical therapy and rehabilitation programs for knee injuries or after knee surgeries.",
    "The rectus abdominis is a long, flat muscle that extends vertically along the front of the abdomen. It's commonly referred to as the abs or six-pack muscle due to its appearance when well-defined. Here are some key points about the rectus abdominis: Location: The rectus abdominis is located between the ribs and the pubic bone, running vertically along the anterior abdominal wall. It is paired, with one muscle on each side of the midline. Function: The main function of the rectus abdominis is to flex the lumbar spine, bringing the ribcage closer to the pelvis. This action is involved in movements such as sit-ups, crunches, and leg raises. Additionally, the rectus abdominis provides stability to the trunk and assists in maintaining proper posture. Structure: The muscle is divided into segments by fibrous bands called tendinous intersections, giving it the appearance of multiple segments or packs in well-defined individuals. Innervation: The rectus abdominis is innervated by the lower six thoracoabdominal nerves (T7-T11) and the subcostal nerve (T12), all of which arise from the thoracic spinal nerves. Training: Strengthening the rectus abdominis is a common goal for those seeking to improve core strength and achieve a toned abdomen. Exercises targeting this muscle include crunches, sit-ups, leg raises, and planks. While the rectus abdominis is well-known for its aesthetic appeal, it also plays a crucial role in providing core stability and supporting various movements and activities in daily life.",
    "The pectoralis major is a large, fan-shaped muscle located in the chest region. Here's an overview: Location: The pectoralis major is situated in the anterior (front) portion of the chest. It spans from the sternum (breastbone) and clavicle (collarbone) to the humerus (upper arm bone). Function: The primary function of the pectoralis major is to bring the arm across the chest (adduction), as well as to rotate the arm inwardly (medial rotation) and to move the arm forward (flexion). It plays a significant role in movements such as pushing, lifting, and hugging. Structure: The muscle has two main portions: the clavicular head (upper portion) and the sternal head (lower portion). The clavicular head originates from the medial half of the clavicle, while the sternal head originates from the sternum, the upper six costal cartilages, and the aponeurosis of the external oblique muscle. Both heads converge and insert into the humerus. Innervation: The pectoralis major is primarily innervated by the medial and lateral pectoral nerves, which originate from the brachial plexus (nerve network in the shoulder region), specifically from the anterior divisions of the upper and middle trunk (C5-T1 spinal nerves). Training: Strengthening the pectoralis major is a common goal in fitness and bodybuilding. Exercises targeting this muscle include bench presses, push-ups, chest flyes, and cable crossovers. These exercises help develop strength, size, and definition in the chest region. Overall, the pectoralis major is a crucial muscle involved in upper body strength and function, contributing to various daily activities and athletic movements.",
    "The pectoralis major is a large, fan-shaped muscle located in the chest region. Here's an overview: Location: The pectoralis major is situated in the anterior (front) portion of the chest. It spans from the sternum (breastbone) and clavicle (collarbone) to the humerus (upper arm bone). Function: The primary function of the pectoralis major is to bring the arm across the chest (adduction), as well as to rotate the arm inwardly (medial rotation) and to move the arm forward (flexion). It plays a significant role in movements such as pushing, lifting, and hugging. Structure: The muscle has two main portions: the clavicular head (upper portion) and the sternal head (lower portion). The clavicular head originates from the medial half of the clavicle, while the sternal head originates from the sternum, the upper six costal cartilages, and the aponeurosis of the external oblique muscle. Both heads converge and insert into the humerus. Innervation: The pectoralis major is primarily innervated by the medial and lateral pectoral nerves, which originate from the brachial plexus (nerve network in the shoulder region), specifically from the anterior divisions of the upper and middle trunk (C5-T1 spinal nerves). Training: Strengthening the pectoralis major is a common goal in fitness and bodybuilding. Exercises targeting this muscle include bench presses, push-ups, chest flyes, and cable crossovers. These exercises help develop strength, size, and definition in the chest region. Overall, the pectoralis major is a crucial muscle involved in upper body strength and function, contributing to various daily activities and athletic movements.",
    "The biceps brachii, commonly known as the biceps, is a prominent muscle located in the front of the upper arm. Here's an overview: Location: The biceps brachii muscle runs along the anterior (front) aspect of the upper arm, between the shoulder and the elbow. Structure: The biceps brachii has two heads: the long head and the short head. The long head originates from the supraglenoid tubercle of the scapula (shoulder blade). The short head originates from the coracoid process of the scapula. Both heads converge to form the main body of the muscle, which inserts into the radius bone in the forearm via the bicipital aponeurosis. Function: The primary function of the biceps brachii is elbow flexion, which means it bends the elbow, bringing the forearm closer to the upper arm. Additionally, the biceps brachii supinates the forearm, meaning it rotates the palm of the hand to face upward. It also assists in shoulder flexion and stabilization of the shoulder joint. Innervation: The biceps brachii is innervated by the musculocutaneous nerve, which arises from the brachial plexus and provides motor innervation to the muscles of the anterior arm. Training: Strengthening the biceps brachii is a common goal in fitness and bodybuilding. Exercises targeting this muscle include biceps curls (with dumbbells, barbells, or cables), hammer curls, chin-ups, and preacher curls. These exercises help to increase muscle mass, strength, and definition in the biceps. The biceps brachii is not only important for aesthetic purposes but also plays a significant role in various daily activities involving lifting, pulling, and gripping.",
    "The biceps brachii, commonly known as the biceps, is a prominent muscle located in the front of the upper arm. Here's an overview: Location: The biceps brachii muscle runs along the anterior (front) aspect of the upper arm, between the shoulder and the elbow. Structure: The biceps brachii has two heads: the long head and the short head. The long head originates from the supraglenoid tubercle of the scapula (shoulder blade). The short head originates from the coracoid process of the scapula. Both heads converge to form the main body of the muscle, which inserts into the radius bone in the forearm via the bicipital aponeurosis. Function: The primary function of the biceps brachii is elbow flexion, which means it bends the elbow, bringing the forearm closer to the upper arm. Additionally, the biceps brachii supinates the forearm, meaning it rotates the palm of the hand to face upward. It also assists in shoulder flexion and stabilization of the shoulder joint. Innervation: The biceps brachii is innervated by the musculocutaneous nerve, which arises from the brachial plexus and provides motor innervation to the muscles of the anterior arm. Training: Strengthening the biceps brachii is a common goal in fitness and bodybuilding. Exercises targeting this muscle include biceps curls (with dumbbells, barbells, or cables), hammer curls, chin-ups, and preacher curls. These exercises help to increase muscle mass, strength, and definition in the biceps. The biceps brachii is not only important for aesthetic purposes but also plays a significant role in various daily activities involving lifting, pulling, and gripping.",
    "Calves: Anatomy: The calves comprise two primary muscles: the gastrocnemius and the soleus. Gastrocnemius: This muscle is the larger of the two and is located on the back of the lower leg. It has two heads, the medial head, and the lateral head, both of which originate from the posterior aspect of the femur (thigh bone). The gastrocnemius inserts into the calcaneus (heel bone) via the Achilles tendon. Soleus: The soleus muscle lies beneath the gastrocnemius. It originates from the tibia (shinbone) and fibula (calf bone) and also inserts into the calcaneus via the Achilles tendon. Function: The primary function of the calf muscles is to plantarflex the foot, meaning they point the foot downward. This action is crucial for activities such as walking, running, jumping, and standing on tiptoe. The gastrocnemius is more involved in activities that require explosive force, such as jumping, while the soleus is more active during endurance activities like walking and standing. Innervation: Both the gastrocnemius and soleus muscles are innervated by the tibial nerve, which arises from the sciatic nerve and provides motor innervation to the muscles of the posterior leg. Training: Strengthening the calves is important for overall lower body strength and stability. Common exercises to target the calves include calf raises (both seated and standing), calf presses on a leg press machine, and jumping exercises such as box jumps and skipping rope. Training the calves helps improve ankle stability, athletic performance, and aesthetics.",
    "Calves: Anatomy: The calves comprise two primary muscles: the gastrocnemius and the soleus. Gastrocnemius: This muscle is the larger of the two and is located on the back of the lower leg. It has two heads, the medial head, and the lateral head, both of which originate from the posterior aspect of the femur (thigh bone). The gastrocnemius inserts into the calcaneus (heel bone) via the Achilles tendon. Soleus: The soleus muscle lies beneath the gastrocnemius. It originates from the tibia (shinbone) and fibula (calf bone) and also inserts into the calcaneus via the Achilles tendon. Function: The primary function of the calf muscles is to plantarflex the foot, meaning they point the foot downward. This action is crucial for activities such as walking, running, jumping, and standing on tiptoe. The gastrocnemius is more involved in activities that require explosive force, such as jumping, while the soleus is more active during endurance activities like walking and standing. Innervation: Both the gastrocnemius and soleus muscles are innervated by the tibial nerve, which arises from the sciatic nerve and provides motor innervation to the muscles of the posterior leg. Training: Strengthening the calves is important for overall lower body strength and stability. Common exercises to target the calves include calf raises (both seated and standing), calf presses on a leg press machine, and jumping exercises such as box jumps and skipping rope. Training the calves helps improve ankle stability, athletic performance, and aesthetics.",
    "Deltoids: Anatomy: The deltoid muscle, commonly referred to as the delts, is a triangular-shaped muscle located on the shoulder. Three Heads: The deltoid has three heads: the anterior (front) deltoid, the medial (side) deltoid, and the posterior (rear) deltoid. Each head has its own origin and contributes to different movements of the shoulder. The anterior deltoid originates from the lateral third of the clavicle. The medial deltoid originates from the acromion process of the scapula. The posterior deltoid originates from the spine of the scapula. Function: The deltoid muscle is responsible for various movements of the shoulder joint. Anterior Deltoid: It assists in shoulder flexion (raising the arm forward), horizontal adduction (bringing the arm across the body), and internal rotation. Medial Deltoid: It primarily abducts the arm (raising the arm to the side). Posterior Deltoid: It aids in shoulder extension (moving the arm backward), horizontal abduction (moving the arm away from the body), and external rotation. Innervation: The deltoid muscle is innervated by the axillary nerve, which arises from the posterior cord of the brachial plexus and provides motor innervation to the deltoid muscle and sensation to part of the shoulder joint. Training: Strengthening the deltoids is crucial for shoulder stability, mobility, and aesthetics. Exercises to target the deltoids include overhead presses (dumbbell, barbell, or machine), lateral raises, front raises, rear delt flyes, and upright rows. Training the deltoids helps improve shoulder strength, posture, and overall upper body function.",
    "Deltoids:Anatomy: The deltoid muscle, commonly referred to as the delts, is a triangular-shaped muscle located on the shoulder. Three Heads: The deltoid has three heads: the anterior (front) deltoid, the medial (side) deltoid, and the posterior (rear) deltoid. Each head has its own origin and contributes to different movements of the shoulder. The anterior deltoid originates from the lateral third of the clavicle. The medial deltoid originates from the acromion process of the scapula. The posterior deltoid originates from the spine of the scapula. Function: The deltoid muscle is responsible for various movements of the shoulder joint. Anterior Deltoid: It assists in shoulder flexion (raising the arm forward), horizontal adduction (bringing the arm across the body), and internal rotation. Medial Deltoid: It primarily abducts the arm (raising the arm to the side). Posterior Deltoid: It aids in shoulder extension (moving the arm backward), horizontal abduction (moving the arm away from the body), and external rotation. Innervation: The deltoid muscle is innervated by the axillary nerve, which arises from the posterior cord of the brachial plexus and provides motor innervation to the deltoid muscle and sensation to part of the shoulder joint. Training: Strengthening the deltoids is crucial for shoulder stability, mobility, and aesthetics. Exercises to target the deltoids include overhead presses (dumbbell, barbell, or machine), lateral raises, front raises, rear delt flyes, and upright rows. Training the deltoids helps improve shoulder strength, posture, and overall upper body function.",
    "Forearms: Anatomy: The forearms contain a complex array of muscles responsible for various movements of the wrist, hand, and fingers. Key muscles include: Flexors: These muscles are located on the anterior (front) side of the forearm and are responsible for flexing the wrist and fingers. Important flexors include the flexor digitorum superficialis, flexor digitorum profundus, and flexor carpi ulnaris. Extensors: Found on the posterior (back) side of the forearm, extensor muscles extend the wrist and fingers. Notable extensors include the extensor digitorum, extensor carpi radialis longus and brevis, and extensor carpi ulnaris. Pronators and Supinators: These muscles are responsible for pronation (turning the palm downward) and supination (turning the palm upward) of the forearm. The pronator teres and pronator quadratus handle pronation, while the supinator handles supination. Function: The forearms play a crucial role in various everyday activities, including gripping, lifting, and manipulating objects. They contribute to both fine motor skills (such as writing and typing) and gross motor skills (such as lifting weights and using tools). Additionally, strong forearms are essential for maintaining grip strength and wrist stability during physical activities. Innervation: The muscles of the forearm are innervated by various nerves originating from the brachial plexus, including the median nerve, ulnar nerve, and radial nerve. These nerves provide motor innervation to the muscles and sensation to the skin of the forearm and hand. Training: Strengthening the forearms is important for improving grip strength, wrist stability, and overall upper extremity function. Exercises to target the forearms include wrist curls (both flexion and extension), reverse wrist curls, grip exercises (such as farmer's walks and plate pinches), and forearm pronation and supination exercises.",
    "Forearms: Anatomy: The forearms contain a complex array of muscles responsible for various movements of the wrist, hand, and fingers. Key muscles include: Flexors: These muscles are located on the anterior (front) side of the forearm and are responsible for flexing the wrist and fingers. Important flexors include the flexor digitorum superficialis, flexor digitorum profundus, and flexor carpi ulnaris. Extensors: Found on the posterior (back) side of the forearm, extensor muscles extend the wrist and fingers. Notable extensors include the extensor digitorum, extensor carpi radialis longus and brevis, and extensor carpi ulnaris. Pronators and Supinators: These muscles are responsible for pronation (turning the palm downward) and supination (turning the palm upward) of the forearm. The pronator teres and pronator quadratus handle pronation, while the supinator handles supination. Function: The forearms play a crucial role in various everyday activities, including gripping, lifting, and manipulating objects. They contribute to both fine motor skills (such as writing and typing) and gross motor skills (such as lifting weights and using tools). Additionally, strong forearms are essential for maintaining grip strength and wrist stability during physical activities. Innervation: The muscles of the forearm are innervated by various nerves originating from the brachial plexus, including the median nerve, ulnar nerve, and radial nerve. These nerves provide motor innervation to the muscles and sensation to the skin of the forearm and hand. Training: Strengthening the forearms is important for improving grip strength, wrist stability, and overall upper extremity function. Exercises to target the forearms include wrist curls (both flexion and extension), reverse wrist curls, grip exercises (such as farmer's walks and plate pinches), and forearm pronation and supination exercises.",
    "Upper Trapezius: Anatomy: The trapezius muscle is a large, triangular-shaped muscle located on the back and neck. It is divided into three regions: the upper, middle, and lower trapezius. The upper trapezius, specifically, is the portion of the muscle that originates from the occipital bone (base of the skull) and the spinous processes of the cervical vertebrae (C1-C4) and inserts into the lateral third of the clavicle (collarbone) and the acromion process of the scapula (shoulder blade). Function: The primary function of the upper trapezius is to elevate the scapula (shoulder blade) and assist in upward rotation of the scapula during movements such as shrugging the shoulders and raising the arms overhead. Additionally, the upper trapezius contributes to neck extension (tilting the head backward) and lateral flexion (bending the head sideways). It plays a crucial role in stabilizing the shoulder girdle and maintaining proper posture. Innervation: The upper trapezius is innervated by the accessory nerve (cranial nerve XI) and branches of the cervical spinal nerves (C3-C4). The accessory nerve provides motor innervation to the trapezius muscles, while the cervical spinal nerves supply sensory innervation. Training: Strengthening the upper trapezius is important for improving shoulder stability, posture, and overall upper body strength. Exercises to target the upper trapezius include: Shrugs: Stand or sit with a weight in each hand (dumbbells or a barbell), and elevate the shoulders toward the ears, then lower them back down. Upright Rows: Hold a barbell or dumbbells with an overhand grip and lift the weight upward, keeping the elbows higher than the wrists and close to the body. Scapular Retraction: Perform exercises that involve squeezing the shoulder blades together, such as seated rows or band pull-aparts. Overhead Presses: Exercises like dumbbell or barbell overhead presses engage the upper trapezius along with other shoulder muscles to raise the arms overhead.",
    "Upper Trapezius: Anatomy: The trapezius muscle is a large, triangular-shaped muscle located on the back and neck. It is divided into three regions: the upper, middle, and lower trapezius. The upper trapezius, specifically, is the portion of the muscle that originates from the occipital bone (base of the skull) and the spinous processes of the cervical vertebrae (C1-C4) and inserts into the lateral third of the clavicle (collarbone) and the acromion process of the scapula (shoulder blade). Function: The primary function of the upper trapezius is to elevate the scapula (shoulder blade) and assist in upward rotation of the scapula during movements such as shrugging the shoulders and raising the arms overhead. Additionally, the upper trapezius contributes to neck extension (tilting the head backward) and lateral flexion (bending the head sideways). It plays a crucial role in stabilizing the shoulder girdle and maintaining proper posture. Innervation: The upper trapezius is innervated by the accessory nerve (cranial nerve XI) and branches of the cervical spinal nerves (C3-C4). The accessory nerve provides motor innervation to the trapezius muscles, while the cervical spinal nerves supply sensory innervation. Training: Strengthening the upper trapezius is important for improving shoulder stability, posture, and overall upper body strength. Exercises to target the upper trapezius include: Shrugs: Stand or sit with a weight in each hand (dumbbells or a barbell), and elevate the shoulders toward the ears, then lower them back down. Upright Rows: Hold a barbell or dumbbells with an overhand grip and lift the weight upward, keeping the elbows higher than the wrists and close to the body. Scapular Retraction: Perform exercises that involve squeezing the shoulder blades together, such as seated rows or band pull-aparts. Overhead Presses: Exercises like dumbbell or barbell overhead presses engage the upper trapezius along with other shoulder muscles to raise the arms overhead.",
    "Obliques (External and Internal Obliques): Anatomy: The obliques are a pair of muscles located on the sides of the abdomen, running diagonally from the lower ribs to the pelvis. There are two main types of oblique muscles: External Obliques: These are the superficial muscles of the lateral abdominal wall. They originate from the lower eight ribs and insert into the linea alba (a fibrous band of tissue that runs vertically down the midline of the abdomen), iliac crest (top ridge of the pelvis), and inguinal ligament (connective tissue in the groin area). Internal Obliques: Positioned beneath the external obliques, the internal obliques have a similar fiber orientation but run in the opposite direction. They originate from the inguinal ligament, iliac crest, and thoracolumbar fascia (connective tissue on the lower back) and insert into the lower ribs and linea alba. Function: The oblique muscles play several important roles in trunk movement and stability: Rotation: Contraction of the obliques on one side causes rotation of the trunk toward that side. Lateral Flexion: Working together, the obliques flex the trunk sideways, allowing you to bend to the side. Compression: When both sides contract simultaneously, the obliques compress the abdomen, assisting in activities such as coughing, sneezing, and expelling air. Innervation: The external obliques are innervated by the lower six thoracoabdominal nerves (T7-T11) and the subcostal nerve (T12), while the internal obliques are innervated by the lower thoracoabdominal nerves (T7-T11). Training: Strengthening the obliques is important for overall core strength, stability, and aesthetics. Exercises targeting the obliques include: Side Planks: Hold a plank position on your side, supporting your body weight on your forearm and feet, and engage your obliques to maintain stability. Russian Twists: Sit on the floor with knees bent, lean back slightly, and rotate your torso from side to side while holding a weight or medicine ball. Bicycle Crunches: Lie on your back, lift your shoulders off the ground, and bring one knee toward the opposite elbow while extending the other leg, alternating sides in a pedaling motion.",
    "Obliques (External and Internal Obliques): Anatomy: The obliques are a pair of muscles located on the sides of the abdomen, running diagonally from the lower ribs to the pelvis. There are two main types of oblique muscles: External Obliques: These are the superficial muscles of the lateral abdominal wall. They originate from the lower eight ribs and insert into the linea alba (a fibrous band of tissue that runs vertically down the midline of the abdomen), iliac crest (top ridge of the pelvis), and inguinal ligament (connective tissue in the groin area). Internal Obliques: Positioned beneath the external obliques, the internal obliques have a similar fiber orientation but run in the opposite direction. They originate from the inguinal ligament, iliac crest, and thoracolumbar fascia (connective tissue on the lower back) and insert into the lower ribs and linea alba. Function: The oblique muscles play several important roles in trunk movement and stability: Rotation: Contraction of the obliques on one side causes rotation of the trunk toward that side. Lateral Flexion: Working together, the obliques flex the trunk sideways, allowing you to bend to the side. Compression: When both sides contract simultaneously, the obliques compress the abdomen, assisting in activities such as coughing, sneezing, and expelling air. Innervation: The external obliques are innervated by the lower six thoracoabdominal nerves (T7-T11) and the subcostal nerve (T12), while the internal obliques are innervated by the lower thoracoabdominal nerves (T7-T11). Training: Strengthening the obliques is important for overall core strength, stability, and aesthetics. Exercises targeting the obliques include: Side Planks: Hold a plank position on your side, supporting your body weight on your forearm and feet, and engage your obliques to maintain stability. Russian Twists: Sit on the floor with knees bent, lean back slightly, and rotate your torso from side to side while holding a weight or medicine ball. Bicycle Crunches: Lie on your back, lift your shoulders off the ground, and bring one knee toward the opposite elbow while extending the other leg, alternating sides in a pedaling motion.",
    "Obliques (External and Internal Obliques): Anatomy: The obliques are a pair of muscles located on the sides of the abdomen, running diagonally from the lower ribs to the pelvis. There are two main types of oblique muscles: External Obliques: These are the superficial muscles of the lateral abdominal wall. They originate from the lower eight ribs and insert into the linea alba (a fibrous band of tissue that runs vertically down the midline of the abdomen), iliac crest (top ridge of the pelvis), and inguinal ligament (connective tissue in the groin area). Internal Obliques: Positioned beneath the external obliques, the internal obliques have a similar fiber orientation but run in the opposite direction. They originate from the inguinal ligament, iliac crest, and thoracolumbar fascia (connective tissue on the lower back) and insert into the lower ribs and linea alba. Function: The oblique muscles play several important roles in trunk movement and stability: Rotation: Contraction of the obliques on one side causes rotation of the trunk toward that side. Lateral Flexion: Working together, the obliques flex the trunk sideways, allowing you to bend to the side. Compression: When both sides contract simultaneously, the obliques compress the abdomen, assisting in activities such as coughing, sneezing, and expelling air. Innervation: The external obliques are innervated by the lower six thoracoabdominal nerves (T7-T11) and the subcostal nerve (T12), while the internal obliques are innervated by the lower thoracoabdominal nerves (T7-T11). Training: Strengthening the obliques is important for overall core strength, stability, and aesthetics. Exercises targeting the obliques include: Side Planks: Hold a plank position on your side, supporting your body weight on your forearm and feet, and engage your obliques to maintain stability. Russian Twists: Sit on the floor with knees bent, lean back slightly, and rotate your torso from side to side while holding a weight or medicine ball. Bicycle Crunches: Lie on your back, lift your shoulders off the ground, and bring one knee toward the opposite elbow while extending the other leg, alternating sides in a pedaling motion.",
    "Obliques (External and Internal Obliques): Anatomy: The obliques are a pair of muscles located on the sides of the abdomen, running diagonally from the lower ribs to the pelvis. There are two main types of oblique muscles: External Obliques: These are the superficial muscles of the lateral abdominal wall. They originate from the lower eight ribs and insert into the linea alba (a fibrous band of tissue that runs vertically down the midline of the abdomen), iliac crest (top ridge of the pelvis), and inguinal ligament (connective tissue in the groin area). Internal Obliques: Positioned beneath the external obliques, the internal obliques have a similar fiber orientation but run in the opposite direction. They originate from the inguinal ligament, iliac crest, and thoracolumbar fascia (connective tissue on the lower back) and insert into the lower ribs and linea alba. Function: The oblique muscles play several important roles in trunk movement and stability: Rotation: Contraction of the obliques on one side causes rotation of the trunk toward that side. Lateral Flexion: Working together, the obliques flex the trunk sideways, allowing you to bend to the side. Compression: When both sides contract simultaneously, the obliques compress the abdomen, assisting in activities such as coughing, sneezing, and expelling air. Innervation: The external obliques are innervated by the lower six thoracoabdominal nerves (T7-T11) and the subcostal nerve (T12), while the internal obliques are innervated by the lower thoracoabdominal nerves (T7-T11). Training: Strengthening the obliques is important for overall core strength, stability, and aesthetics. Exercises targeting the obliques include: Side Planks: Hold a plank position on your side, supporting your body weight on your forearm and feet, and engage your obliques to maintain stability. Russian Twists: Sit on the floor with knees bent, lean back slightly, and rotate your torso from side to side while holding a weight or medicine ball. Bicycle Crunches: Lie on your back, lift your shoulders off the ground, and bring one knee toward the opposite elbow while extending the other leg, alternating sides in a pedaling motion.",
];
var backMusclesParagraphs = [
    "Anatomy: The hamstrings consist of three main muscles: Biceps Femoris: This muscle is divided into two heads: the long head and the short head. The long head originates from the ischial tuberosity (sit bones) of the pelvis, while the short head originates from the back of the femur (thigh bone). Both heads converge and insert into the head of the fibula (calf bone) and the lateral side of the tibia (shinbone). Semitendinosus: This muscle originates from the ischial tuberosity and inserts into the medial aspect of the upper tibia. Semimembranosus: Like the semitendinosus, this muscle also originates from the ischial tuberosity but inserts into the posterior aspect of the medial condyle of the tibia. Function: The hamstrings have several important functions, including: Knee Flexion: They bend the knee, bringing the heel toward the buttocks. Hip Extension: They assist in extending the hip, moving the thigh backward. Stabilization: The hamstrings play a role in stabilizing both the knee and the hip joint during movement and weight-bearing activities. Innervation: The hamstrings are innervated by the sciatic nerve, specifically its branches: the tibial nerve and the common fibular nerve. These nerves arise from the lumbar and sacral spinal nerves (L4-S3). Training: Strengthening the hamstrings is important for overall lower body strength, stability, and injury prevention. Exercises to target the hamstrings include: Deadlifts: Both conventional and Romanian deadlifts engage the hamstrings along with other muscles in the posterior chain. Lying Leg Curls: This exercise specifically targets knee flexion, isolating the hamstrings. Good Mornings: This exercise involves bending forward at the hips while keeping the back straight, which engages the hamstrings and glutes. Glute-Ham Raises: This exercise focuses on knee flexion against resistance, strengthening the hamstrings.",
    "Anatomy: The hamstrings consist of three main muscles: Biceps Femoris: This muscle is divided into two heads: the long head and the short head. The long head originates from the ischial tuberosity (sit bones) of the pelvis, while the short head originates from the back of the femur (thigh bone). Both heads converge and insert into the head of the fibula (calf bone) and the lateral side of the tibia (shinbone). Semitendinosus: This muscle originates from the ischial tuberosity and inserts into the medial aspect of the upper tibia. Semimembranosus: Like the semitendinosus, this muscle also originates from the ischial tuberosity but inserts into the posterior aspect of the medial condyle of the tibia. Function: The hamstrings have several important functions, including: Knee Flexion: They bend the knee, bringing the heel toward the buttocks. Hip Extension: They assist in extending the hip, moving the thigh backward. Stabilization: The hamstrings play a role in stabilizing both the knee and the hip joint during movement and weight-bearing activities. Innervation: The hamstrings are innervated by the sciatic nerve, specifically its branches: the tibial nerve and the common fibular nerve. These nerves arise from the lumbar and sacral spinal nerves (L4-S3). Training: Strengthening the hamstrings is important for overall lower body strength, stability, and injury prevention. Exercises to target the hamstrings include: Deadlifts: Both conventional and Romanian deadlifts engage the hamstrings along with other muscles in the posterior chain. Lying Leg Curls: This exercise specifically targets knee flexion, isolating the hamstrings. Good Mornings: This exercise involves bending forward at the hips while keeping the back straight, which engages the hamstrings and glutes. Glute-Ham Raises: This exercise focuses on knee flexion against resistance, strengthening the hamstrings.",
    "Gluteal Muscles: Anatomy: The glutes, or gluteal muscles, are a group of three muscles located in the buttocks region: Gluteus Maximus: This is the largest and most superficial of the three gluteal muscles. It originates from the ilium (hip bone), sacrum, and coccyx (tailbone) and inserts into the iliotibial band and the gluteal tuberosity of the femur. Gluteus Medius: Positioned on the outer surface of the pelvis, this muscle originates from the ilium and inserts into the greater trochanter of the femur. Gluteus Minimus: Located beneath the gluteus medius, it has a similar origin and insertion to the gluteus medius. Function: The gluteal muscles play several important roles: Hip Extension: The gluteus maximus primarily extends the thigh at the hip joint, moving the leg backward. Hip Abduction: The gluteus medius and minimus are primarily responsible for moving the thigh away from the midline of the body. Pelvic Stability: All three gluteal muscles contribute to stabilizing the pelvis during various movements, including walking, running, and standing. Innervation: The gluteal muscles are innervated by the superior gluteal nerve, which arises from the sacral plexus (nerve network in the lower back) and provides motor innervation to the muscles. Training: Strengthening the glutes is important for lower body strength, stability, and overall athletic performance. Exercises to target the glutes include squats, lunges, deadlifts, hip thrusts, glute bridges, and various abduction exercises using resistance bands or machines.",
    "Lower Back (Including Psoas Muscles): Anatomy: The lower back region includes several muscles, with the psoas major being one of the key muscles involved. The psoas major, along with the iliacus muscle, forms the iliopsoas complex. The psoas major originates from the lumbar vertebrae and inserts into the lesser trochanter of the femur. Function: The primary function of the psoas muscles is hip flexion, which involves bringing the thigh toward the torso. Additionally, the psoas muscles play a role in stabilizing the spine and pelvis during movements such as walking, running, and standing. Innervation: The psoas major is innervated by branches of the lumbar spinal nerves (L1-L3), specifically the anterior rami of these nerves. Training: Strengthening the lower back muscles, including the psoas, is important for maintaining spinal stability and preventing lower back pain or injury. Exercises to target the lower back include deadlifts, hyperextensions, good mornings, and various core exercises such as planks and bird dogs",
    "Lower Trapezius: Anatomy: The trapezius muscle is a large, triangular-shaped muscle located on the upper back and neck. It is divided into three regions: the upper, middle, and lower trapezius. The lower trapezius is the portion of the muscle that originates from the spinous processes of the thoracic vertebrae (T1-T4) and inserts into the spine of the scapula (shoulder blade) and the acromion process of the scapula. Function: The lower trapezius plays several important roles in shoulder movement and stability: Scapular Retraction: Contraction of the lower trapezius pulls the scapula toward the spine, squeezing the shoulder blades together. Scapular Depression: The lower trapezius also assists in depressing the scapula, moving it downward. Scapular Upward Rotation: Working together with other muscles, the lower trapezius helps rotate the scapula upward during movements such as raising the arms overhead. Innervation: The lower trapezius is innervated by the accessory nerve (cranial nerve XI) and branches of the cervical spinal nerves (C3-C4). The accessory nerve provides motor innervation to the trapezius muscles, while the cervical spinal nerves supply sensory innervation. Training: Strengthening the lower trapezius is important for maintaining shoulder health, improving posture, and reducing the risk of shoulder injuries. Exercises to target the lower trapezius include: Prone Y-Raises: Lie face down on a bench or mat, with arms extended overhead in a Y-shape. Lift the arms toward the ceiling, engaging the lower trapezius muscles. Face Pulls: Attach a resistance band or cable to a high anchor point. Pull the band or cable toward your face, focusing on squeezing the shoulder blades together. Reverse Flyes: Perform reverse flyes using dumbbells or a machine, with a focus on squeezing the shoulder blades together at the top of the movement. Rowing Variations: Include rowing exercises such as seated rows, bent-over rows, or cable rows in your workout routine to engage the lower trapezius along with other back muscles.",
    "Triceps Brachii: Anatomy: The triceps brachii, commonly known as the triceps, is a three-headed muscle located on the back of the upper arm. It consists of three heads: Long Head: Originates from the scapula (shoulder blade) and runs down the back of the arm. Lateral Head: Originates from the posterior surface of the humerus (upper arm bone) and is located on the outer side of the arm. Medial Head: Originates from the posterior surface of the humerus, beneath the lateral head, and is located on the inner side of the arm. Function: The primary function of the triceps brachii is to extend the elbow joint, straightening the arm. It also contributes to stabilizing the shoulder joint during movements such as pushing and lifting. Innervation: The triceps brachii is innervated by the radial nerve, which arises from the brachial plexus and provides motor innervation to the muscles of the posterior arm. Training: Strengthening the triceps is important for overall upper body strength and aesthetics, as well as for performing pushing movements effectively. Exercises to target the triceps include triceps dips, triceps pushdowns, overhead triceps extensions, close-grip bench presses, and skull crushers.",
    "Triceps Brachii: Anatomy: The triceps brachii, commonly known as the triceps, is a three-headed muscle located on the back of the upper arm. It consists of three heads: Long Head: Originates from the scapula (shoulder blade) and runs down the back of the arm. Lateral Head: Originates from the posterior surface of the humerus (upper arm bone) and is located on the outer side of the arm. Medial Head: Originates from the posterior surface of the humerus, beneath the lateral head, and is located on the inner side of the arm. Function: The primary function of the triceps brachii is to extend the elbow joint, straightening the arm. It also contributes to stabilizing the shoulder joint during movements such as pushing and lifting. Innervation: The triceps brachii is innervated by the radial nerve, which arises from the brachial plexus and provides motor innervation to the muscles of the posterior arm. Training: Strengthening the triceps is important for overall upper body strength and aesthetics, as well as for performing pushing movements effectively. Exercises to target the triceps include triceps dips, triceps pushdowns, overhead triceps extensions, close-grip bench presses, and skull crushers.",
    "Calves: Anatomy: The calves comprise two primary muscles: the gastrocnemius and the soleus. Gastrocnemius: This muscle is the larger of the two and is located on the back of the lower leg. It has two heads, the medial head, and the lateral head, both of which originate from the posterior aspect of the femur (thigh bone). The gastrocnemius inserts into the calcaneus (heel bone) via the Achilles tendon. Soleus: The soleus muscle lies beneath the gastrocnemius. It originates from the tibia (shinbone) and fibula (calf bone) and also inserts into the calcaneus via the Achilles tendon. Function: The primary function of the calf muscles is to plantarflex the foot, meaning they point the foot downward. This action is crucial for activities such as walking, running, jumping, and standing on tiptoe. The gastrocnemius is more involved in activities that require explosive force, such as jumping, while the soleus is more active during endurance activities like walking and standing. Innervation: Both the gastrocnemius and soleus muscles are innervated by the tibial nerve, which arises from the sciatic nerve and provides motor innervation to the muscles of the posterior leg. Training: Strengthening the calves is important for overall lower body strength and stability. Common exercises to target the calves include calf raises (both seated and standing), calf presses on a leg press machine, and jumping exercises such as box jumps and skipping rope. Training the calves helps improve ankle stability, athletic performance, and aesthetics.",
    "Calves: Anatomy: The calves comprise two primary muscles: the gastrocnemius and the soleus. Gastrocnemius: This muscle is the larger of the two and is located on the back of the lower leg. It has two heads, the medial head, and the lateral head, both of which originate from the posterior aspect of the femur (thigh bone). The gastrocnemius inserts into the calcaneus (heel bone) via the Achilles tendon. Soleus: The soleus muscle lies beneath the gastrocnemius. It originates from the tibia (shinbone) and fibula (calf bone) and also inserts into the calcaneus via the Achilles tendon. Function: The primary function of the calf muscles is to plantarflex the foot, meaning they point the foot downward. This action is crucial for activities such as walking, running, jumping, and standing on tiptoe. The gastrocnemius is more involved in activities that require explosive force, such as jumping, while the soleus is more active during endurance activities like walking and standing. Innervation: Both the gastrocnemius and soleus muscles are innervated by the tibial nerve, which arises from the sciatic nerve and provides motor innervation to the muscles of the posterior leg. Training: Strengthening the calves is important for overall lower body strength and stability. Common exercises to target the calves include calf raises (both seated and standing), calf presses on a leg press machine, and jumping exercises such as box jumps and skipping rope. Training the calves helps improve ankle stability, athletic performance, and aesthetics.",
    "Deltoids: Anatomy: The deltoid muscle, commonly referred to as the delts, is a triangular-shaped muscle located on the shoulder. Three Heads: The deltoid has three heads: the anterior (front) deltoid, the medial (side) deltoid, and the posterior (rear) deltoid. Each head has its own origin and contributes to different movements of the shoulder. The anterior deltoid originates from the lateral third of the clavicle. The medial deltoid originates from the acromion process of the scapula. The posterior deltoid originates from the spine of the scapula. Function: The deltoid muscle is responsible for various movements of the shoulder joint. Anterior Deltoid: It assists in shoulder flexion (raising the arm forward), horizontal adduction (bringing the arm across the body), and internal rotation. Medial Deltoid: It primarily abducts the arm (raising the arm to the side). Posterior Deltoid: It aids in shoulder extension (moving the arm backward), horizontal abduction (moving the arm away from the body), and external rotation. Innervation: The deltoid muscle is innervated by the axillary nerve, which arises from the posterior cord of the brachial plexus and provides motor innervation to the deltoid muscle and sensation to part of the shoulder joint. Training: Strengthening the deltoids is crucial for shoulder stability, mobility, and aesthetics. Exercises to target the deltoids include overhead presses (dumbbell, barbell, or machine), lateral raises, front raises, rear delt flyes, and upright rows. Training the deltoids helps improve shoulder strength, posture, and overall upper body function.",
    "Deltoids: Anatomy: The deltoid muscle, commonly referred to as the delts, is a triangular-shaped muscle located on the shoulder. Three Heads: The deltoid has three heads: the anterior (front) deltoid, the medial (side) deltoid, and the posterior (rear) deltoid. Each head has its own origin and contributes to different movements of the shoulder. The anterior deltoid originates from the lateral third of the clavicle. The medial deltoid originates from the acromion process of the scapula. The posterior deltoid originates from the spine of the scapula. Function: The deltoid muscle is responsible for various movements of the shoulder joint. Anterior Deltoid: It assists in shoulder flexion (raising the arm forward), horizontal adduction (bringing the arm across the body), and internal rotation. Medial Deltoid: It primarily abducts the arm (raising the arm to the side). Posterior Deltoid: It aids in shoulder extension (moving the arm backward), horizontal abduction (moving the arm away from the body), and external rotation. Innervation: The deltoid muscle is innervated by the axillary nerve, which arises from the posterior cord of the brachial plexus and provides motor innervation to the deltoid muscle and sensation to part of the shoulder joint. Training: Strengthening the deltoids is crucial for shoulder stability, mobility, and aesthetics. Exercises to target the deltoids include overhead presses (dumbbell, barbell, or machine), lateral raises, front raises, rear delt flyes, and upright rows. Training the deltoids helps improve shoulder strength, posture, and overall upper body function.",
    "Forearms: Anatomy: The forearms contain a complex array of muscles responsible for various movements of the wrist, hand, and fingers. Key muscles include: Flexors: These muscles are located on the anterior (front) side of the forearm and are responsible for flexing the wrist and fingers. Important flexors include the flexor digitorum superficialis, flexor digitorum profundus, and flexor carpi ulnaris. Extensors: Found on the posterior (back) side of the forearm, extensor muscles extend the wrist and fingers. Notable extensors include the extensor digitorum, extensor carpi radialis longus and brevis, and extensor carpi ulnaris. Pronators and Supinators: These muscles are responsible for pronation (turning the palm downward) and supination (turning the palm upward) of the forearm. The pronator teres and pronator quadratus handle pronation, while the supinator handles supination. Function: The forearms play a crucial role in various everyday activities, including gripping, lifting, and manipulating objects. They contribute to both fine motor skills (such as writing and typing) and gross motor skills (such as lifting weights and using tools). Additionally, strong forearms are essential for maintaining grip strength and wrist stability during physical activities. Innervation: The muscles of the forearm are innervated by various nerves originating from the brachial plexus, including the median nerve, ulnar nerve, and radial nerve. These nerves provide motor innervation to the muscles and sensation to the skin of the forearm and hand. Training: Strengthening the forearms is important for improving grip strength, wrist stability, and overall upper extremity function. Exercises to target the forearms include wrist curls (both flexion and extension), reverse wrist curls, grip exercises (such as farmer's walks and plate pinches), and forearm pronation and supination exercises.",
    "Forearms: Anatomy: The forearms contain a complex array of muscles responsible for various movements of the wrist, hand, and fingers. Key muscles include: Flexors: These muscles are located on the anterior (front) side of the forearm and are responsible for flexing the wrist and fingers. Important flexors include the flexor digitorum superficialis, flexor digitorum profundus, and flexor carpi ulnaris. Extensors: Found on the posterior (back) side of the forearm, extensor muscles extend the wrist and fingers. Notable extensors include the extensor digitorum, extensor carpi radialis longus and brevis, and extensor carpi ulnaris. Pronators and Supinators: These muscles are responsible for pronation (turning the palm downward) and supination (turning the palm upward) of the forearm. The pronator teres and pronator quadratus handle pronation, while the supinator handles supination. Function: The forearms play a crucial role in various everyday activities, including gripping, lifting, and manipulating objects. They contribute to both fine motor skills (such as writing and typing) and gross motor skills (such as lifting weights and using tools). Additionally, strong forearms are essential for maintaining grip strength and wrist stability during physical activities. Innervation: The muscles of the forearm are innervated by various nerves originating from the brachial plexus, including the median nerve, ulnar nerve, and radial nerve. These nerves provide motor innervation to the muscles and sensation to the skin of the forearm and hand. Training: Strengthening the forearms is important for improving grip strength, wrist stability, and overall upper extremity function. Exercises to target the forearms include wrist curls (both flexion and extension), reverse wrist curls, grip exercises (such as farmer's walks and plate pinches), and forearm pronation and supination exercises.",
    "Upper Trapezius: Anatomy: The trapezius muscle is a large, triangular-shaped muscle located on the back and neck. It is divided into three regions: the upper, middle, and lower trapezius. The upper trapezius, specifically, is the portion of the muscle that originates from the occipital bone (base of the skull) and the spinous processes of the cervical vertebrae (C1-C4) and inserts into the lateral third of the clavicle (collarbone) and the acromion process of the scapula (shoulder blade). Function: The primary function of the upper trapezius is to elevate the scapula (shoulder blade) and assist in upward rotation of the scapula during movements such as shrugging the shoulders and raising the arms overhead. Additionally, the upper trapezius contributes to neck extension (tilting the head backward) and lateral flexion (bending the head sideways). It plays a crucial role in stabilizing the shoulder girdle and maintaining proper posture. Innervation: The upper trapezius is innervated by the accessory nerve (cranial nerve XI) and branches of the cervical spinal nerves (C3-C4). The accessory nerve provides motor innervation to the trapezius muscles, while the cervical spinal nerves supply sensory innervation. Training: Strengthening the upper trapezius is important for improving shoulder stability, posture, and overall upper body strength. Exercises to target the upper trapezius include: Shrugs: Stand or sit with a weight in each hand (dumbbells or a barbell), and elevate the shoulders toward the ears, then lower them back down. Upright Rows: Hold a barbell or dumbbells with an overhand grip and lift the weight upward, keeping the elbows higher than the wrists and close to the body. Scapular Retraction: Perform exercises that involve squeezing the shoulder blades together, such as seated rows or band pull-aparts. Overhead Presses: Exercises like dumbbell or barbell overhead presses engage the upper trapezius along with other shoulder muscles to raise the arms overhead.",
    "Anatomy: The latissimus dorsi, commonly referred to as the lats, is the largest muscle in the upper body and is located on the back. It has a broad, fan-like shape and spans from the lower back to the upper arm. Origin: The lats originate from several points along the spine, including the thoracic and lumbar vertebrae, as well as the iliac crest of the pelvis. Insertion: The muscle inserts into the humerus (upper arm bone) via a tendon that wraps around the inferior portion of the armpit. Function: The primary functions of the latissimus dorsi include shoulder extension (pulling the upper arm downward and backward), shoulder adduction (bringing the upper arm toward the body), and shoulder medial rotation. These actions are involved in various pulling movements such as pull-ups, chin-ups, rows, and lat pulldowns. Additionally, the lats contribute to trunk stabilization and posture. Innervation: The latissimus dorsi is innervated by the thoracodorsal nerve (also known as the middle subscapular nerve), which arises from the brachial plexus and provides motor innervation to the muscle. Training: Strengthening the latissimus dorsi is important for improving overall back strength, posture, and upper body aesthetics. Exercises to target the lats include pull-ups, chin-ups, lat pulldowns, rows (such as bent-over rows and seated cable rows), and pullovers. These exercises help develop a strong, well-defined back and contribute to a balanced upper body musculature.",
    "Anatomy: The latissimus dorsi, commonly referred to as the lats, is the largest muscle in the upper body and is located on the back. It has a broad, fan-like shape and spans from the lower back to the upper arm. Origin: The lats originate from several points along the spine, including the thoracic and lumbar vertebrae, as well as the iliac crest of the pelvis. Insertion: The muscle inserts into the humerus (upper arm bone) via a tendon that wraps around the inferior portion of the armpit. Function: The primary functions of the latissimus dorsi include shoulder extension (pulling the upper arm downward and backward), shoulder adduction (bringing the upper arm toward the body), and shoulder medial rotation. These actions are involved in various pulling movements such as pull-ups, chin-ups, rows, and lat pulldowns. Additionally, the lats contribute to trunk stabilization and posture. Innervation: The latissimus dorsi is innervated by the thoracodorsal nerve (also known as the middle subscapular nerve), which arises from the brachial plexus and provides motor innervation to the muscle. Training: Strengthening the latissimus dorsi is important for improving overall back strength, posture, and upper body aesthetics. Exercises to target the lats include pull-ups, chin-ups, lat pulldowns, rows (such as bent-over rows and seated cable rows), and pullovers. These exercises help develop a strong, well-defined back and contribute to a balanced upper body musculature.",
    "Anatomy: The latissimus dorsi, commonly referred to as the lats, is the largest muscle in the upper body and is located on the back. It has a broad, fan-like shape and spans from the lower back to the upper arm. Origin: The lats originate from several points along the spine, including the thoracic and lumbar vertebrae, as well as the iliac crest of the pelvis. Insertion: The muscle inserts into the humerus (upper arm bone) via a tendon that wraps around the inferior portion of the armpit. Function: The primary functions of the latissimus dorsi include shoulder extension (pulling the upper arm downward and backward), shoulder adduction (bringing the upper arm toward the body), and shoulder medial rotation. These actions are involved in various pulling movements such as pull-ups, chin-ups, rows, and lat pulldowns. Additionally, the lats contribute to trunk stabilization and posture. Innervation: The latissimus dorsi is innervated by the thoracodorsal nerve (also known as the middle subscapular nerve), which arises from the brachial plexus and provides motor innervation to the muscle. Training: Strengthening the latissimus dorsi is important for improving overall back strength, posture, and upper body aesthetics. Exercises to target the lats include pull-ups, chin-ups, lat pulldowns, rows (such as bent-over rows and seated cable rows), and pullovers. These exercises help develop a strong, well-defined back and contribute to a balanced upper body musculature.",
    "Anatomy: The latissimus dorsi, commonly referred to as the lats, is the largest muscle in the upper body and is located on the back. It has a broad, fan-like shape and spans from the lower back to the upper arm. Origin: The lats originate from several points along the spine, including the thoracic and lumbar vertebrae, as well as the iliac crest of the pelvis. Insertion: The muscle inserts into the humerus (upper arm bone) via a tendon that wraps around the inferior portion of the armpit. Function: The primary functions of the latissimus dorsi include shoulder extension (pulling the upper arm downward and backward), shoulder adduction (bringing the upper arm toward the body), and shoulder medial rotation. These actions are involved in various pulling movements such as pull-ups, chin-ups, rows, and lat pulldowns. Additionally, the lats contribute to trunk stabilization and posture. Innervation: The latissimus dorsi is innervated by the thoracodorsal nerve (also known as the middle subscapular nerve), which arises from the brachial plexus and provides motor innervation to the muscle. Training: Strengthening the latissimus dorsi is important for improving overall back strength, posture, and upper body aesthetics. Exercises to target the lats include pull-ups, chin-ups, lat pulldowns, rows (such as bent-over rows and seated cable rows), and pullovers. These exercises help develop a strong, well-defined back and contribute to a balanced upper body musculature.",
];

var frontMusclesArray = [bodyQuadracepsOne, bodyQuadracepsTwo, bodyAbdominis, bodyChestOne, bodyChestTwo, bodyBicepsOne, bodyBicepsTwo, bodyCalvesOne, bodyCalvesTwo, bodyDeltoidsOne, bodyDeltoidsTwo, bodyForearmsOne, bodyForearmsTwo,bodyTrapsOne, bodyTrapsTwo, bodyObliquesOne, bodyObliquesTwo, bodyObliquesThree, bodyObliquesFour];
var frontMusclesPicArray = [quadracepsPicture,quadracepsPicture,abdominisPicture,chestPicture,chestPicture,bicepsPicture,bicepsPicture,calvesPicture,calvesPicture,deltoidsPicture,deltoidsPicture,forearmsPicture,forearmsPicture,trapsPicture,trapsPicture,obliquesPicture,obliquesPicture,obliquesPicture,obliquesPicture];
var backMusclesArray = [bodyHamstringsOne, bodyHamstringsTwo, bodyGlutes, bodyLowerBack, bodyLowerTraps, bodyTricepsOne, bodyTricepsTwo, bodyBackCalvesOne, bodyBackCalvesTwo, bodyBackDeltoidsOne, bodyBackDeltoidsTwo, bodyBackForearmsOne, bodyBackForearmsTwo, bodyBackTraps, bodyBackLatsOne, bodyBackLatsTwo, bodyBackLatsThree, bodyBackLatsFour];
var backMusclesPicArray = [hamstringsPicture,hamstringsPicture,glutesPicture,lowerBackPicture,lowerTrapsPicture,tricepsPicture,tricepsPicture,calvesPicture,calvesPicture,deltoidsPicture,deltoidsPicture,forearmsPicture,forearmsPicture,trapsPicture,latsPicture,latsPicture,latsPicture,latsPicture];
var frontMusclesNamesArray = ["Quadriceps", "Quadriceps", "Rectus Abdominis", "Chest", "Chest", "Biceps", "Biceps", "Calves", "Calves", "Deltoids", "Deltoids", "Forearms", "Forearms", "Trapezuis", "Trapezuis", "Obliques", "Obliques", "Obliques", "Obliques"];
var backMusclesNamesArray = ["Hamstrings", "Hamstrings", "Glutes", "Lower back", "Lower traps","Triceps","Triceps","Calves","Calves","Deltoids","Deltoids","Forearms","Forearms","Trapezuis","latissimus","latissimus","latissimus","latissimus"];