var nutritionQuestionsArray = [
    "What is the primary function of carbohydrates in the body?",
    "Which mineral is essential for the formation of hemoglobin in red blood cells?",
    "What is the main source of omega-3 fatty acids?",
    "Which nutrient is known as the body's main energy currency?",
    "What is the role of vitamin K in the body?",
    "Which food is a good source of vitamin C?",
    "What is the recommended daily intake of water for adults?",
    "Which type of fiber is found in fruits, vegetables, and whole grains?",
    "What is the function of calcium in the body?",
    "What is the primary function of the liver in the digestive system?",
    "Which vitamin is synthesized by the skin when exposed to sunlight?",
    "What is the recommended daily intake of protein for sedentary adults?",
    "Which nutrient is crucial for the formation and maintenance of healthy skin?",
    "What is the main function of antioxidants in the body?",
    "Which macronutrient is the body's preferred source of energy during prolonged exercise?",
    "What is the main role of potassium in the body?",
    "Which mineral is essential for proper nerve function?",
    "What is the recommended daily intake of fiber for adults?",
    "What is the difference between soluble and insoluble fiber?",
    "Which food is a good source of iron?",
    "What is the main function of vitamin E in the body?",
    "What is the significance of the glycemic index in nutrition?",
    "Which nutrient is essential for the formation of strong bones and teeth?",
    "What is the main function of phosphorus in the body?",
    "Which type of fat is considered heart-healthy?",
    "What is the role of magnesium in muscle function?",
    "Which vitamin is important for blood clotting?",
    "What is the primary function of dietary fiber?",
    "Which food is a good source of omega-3 fatty acids?",
    "What is the recommended daily intake of sodium for adults?",
    "Which nutrient is a component of every cell in the body?",
    "What is the main function of zinc in the body?",
    "What is the significance of the term 'empty calories'?",
    "Which nutrient provides the most energy per gram?",
    "What is the role of folate (vitamin B9) in the body?",
    "Which food is a good source of potassium?",
    "What is the recommended daily intake of vitamin A for adults?",
    "Which nutrient is important for the synthesis of neurotransmitters in the brain?",
    "What is the function of iodine in the body?",
    "Which type of carbohydrates are found in whole grains, fruits, and vegetables?",
    "What is the main source of vitamin D?",
    "What is the recommended daily intake of calcium for adults?",
    "Which mineral is essential for normal thyroid function?",
    "What is the role of chromium in the body?",
    "Which nutrient is important for the maintenance of healthy eyes?",
    "What is the primary function of sulfur in the body?",
    "Which food is a good source of vitamin K?",
    "What is the recommended daily intake of vitamin C for adults?",
    "Which type of fat is often solid at room temperature?",
    "What is the main function of manganese in the body?"
];

var workoutQuestionsArray = [
    "What type of exercise involves using external resistance, such as dumbbells or barbells?",
    "Which muscle group do squats primarily target?",
    "When is the best time to stretch for flexibility?",
    "What is the correct sequence for a well-rounded workout program?",
    "Which exercise is an effective bodyweight workout for the upper body?",
    "What is the term for the number of times an exercise is performed, usually in sets and repetitions?",
    "Which workout method emphasizes using your own body weight for resistance?",
    "What is the purpose of a warm-up before exercise?",
    "How long should a typical cardio workout last for cardiovascular health?",
    "Which type of exercise promotes joint flexibility and muscle endurance through rhythmic movements?",
    "What is the ideal duration for a high-intensity interval training (HIIT) session?",
    "What is the primary benefit of core exercises?",
    "Which type of stretching is best suited for post-workout cool-down?",
    "What is the recommended frequency for strength training workouts per week?",
    "What is the term for the gradual increase in exercise intensity to prepare the body for a workout?",
    "Which fitness component does flexibility fall under?",
    "How does proper hydration contribute to a workout?",
    "What is the purpose of a cooldown after exercise?",
    "Which exercise targets the muscles in the back of the upper arms?",
    "When aiming for muscle hypertrophy, what rep range is commonly recommended?",
    "What is the primary focus of Pilates exercises?",
    "Which type of exercise helps improve balance and flexibility through slow, controlled movements?",
    "How does resistance training contribute to weight management?",
    "What is the importance of proper breathing during exercise?",
    "Which type of exercise is beneficial for improving cardiovascular endurance?",
    "What is the term for the feeling of discomfort or fatigue during exercise?",
    "How does proper footwear contribute to a safe workout?",
    "What is the recommended duration for a power nap to enhance workout performance?",
    "Which workout intensity zone is often associated with fat burning?",
    "What is the primary muscle worked during a deadlift?",
    "Which factor is crucial for muscle recovery and growth after strength training?",
    "How does cross-training benefit overall fitness?",
    "What is the purpose of including balance exercises in a workout routine?",
    "Which type of exercise involves rapid, repetitive muscle contractions without a full range of motion?",
    "What is the recommended rest time between sets for muscle hypertrophy?",
    "Which exercise primarily targets the quadriceps muscles?",
    "When is the best time to consume protein for muscle repair and recovery?",
    "What is the term for the excessive loss of body fluids through sweating during exercise?",
    "Which nutrient is particularly important for replenishing electrolytes lost during intense workouts?",
    "What is the significance of the RPE (Rate of Perceived Exertion) scale?",
    "Which workout method emphasizes controlled movements and proper alignment?",
    "What is the importance of proper posture during weightlifting?",
    "Which type of exercise involves continuous, steady-state activity for an extended period?",
    "How does proper nutrition contribute to workout performance?",
    "What is the role of a spotter during weightlifting exercises?",
    "Which exercise targets the muscles of the chest?",
    "When is the optimal time to perform static stretching?",
    "What is the recommended frequency for cardio workouts per week?",
    "Which workout principle involves gradually increasing the workload to see continued improvement?",
    "What is the primary purpose of a fitness assessment?",
    "Which muscle group is targeted by lateral raises?",
    "How does progressive overload contribute to muscle development?",
    "What is the term for the ability of a joint to move through its full range of motion?",
    "Which exercise primarily works the muscles of the hamstrings?",
    "What is the importance of a cool-down after a high-intensity workout?",
    "Which factor is crucial for preventing muscle imbalances in a workout routine?",
    "What is the main objective of a dynamic warm-up before exercise?",
    "Which type of exercise is known for promoting relaxation and stress reduction?",
];

var anatomyQuestionsArray = [
    "Which organ is responsible for detoxifying the blood, storing glycogen, and producing proteins?",
    "What is the largest bone in the human body?",
    "Which part of the brain is responsible for regulating basic bodily functions such as breathing and heartbeat?",
    "What is the main function of the respiratory system?",
    "Which muscle is responsible for pumping blood throughout the body?",
    "What is the purpose of the small intestine in the digestive system?",
    "Which type of joint allows for the widest range of motion?",
    "What is the function of the red blood cells in the circulatory system?",
    "Which gland is often referred to as the 'master gland' for its role in regulating other endocrine glands?",
    "What is the purpose of the cerebrospinal fluid in the nervous system?",
    "Which bone protects the brain?",
    "What is the primary function of the urinary system?",
    "Which organ produces insulin and glucagon to regulate blood sugar levels?",
    "What is the role of the pancreas in digestion?",
    "Which type of muscle is under voluntary control?",
    "What is the function of the lymphatic system?",
    "Which bone is commonly known as the collarbone?",
    "What is the function of the thymus gland in the immune system?",
    "Which part of the eye is responsible for controlling the amount of light that enters?",
    "What is the primary function of the spleen?",
    "Which part of the nervous system controls involuntary bodily functions like heart rate and digestion?",
    "What is the function of the epiglottis in the respiratory system?",
    "Which joint connects the arm to the shoulder?",
    "What is the purpose of the gallbladder in digestion?",
    "Which muscle allows you to lift your arm sideways?",
    "What is the largest organ of the human body?",
    "Which part of the ear is responsible for hearing?",
    "What is the function of the thyroid gland?",
    "Which bone is commonly known as the shinbone?",
    "What is the main function of the immune system?",
    "Which organ produces bile for digestion?",
    "What is the purpose of the alveoli in the respiratory system?",
    "Which part of the brain is associated with emotions and memory?",
    "What is the role of the cornea in vision?",
    "Which bone protects the spinal cord?",
    "What is the function of the trachea in the respiratory system?",
    "Which joint allows for flexion and extension movements?",
    "What is the purpose of the synovial fluid in joints?",
    "Which muscle is responsible for bending the arm at the elbow?",
    "What is the function of the adrenal glands?",
    "Which part of the digestive system is responsible for nutrient absorption?",
    "What is the main function of the reproductive system?",
    "Which bone is commonly known as the tailbone?",
    "What is the function of the endocrine system?",
    "Which part of the eye contains cells that detect light and color?",
    "What is the primary function of the male reproductive system?",
    "Which organ filters and cleans the blood, removing toxins?",
    "What is the purpose of the meninges in the nervous system?",
    "Which joint allows for rotation movements?",
];
  
var nutritionOptionsArray = [
    ["Provide energy", "Build muscle", "Support immune function", "Aid in digestion"],
    ["Iron", "Calcium", "Magnesium", "Zinc"],
    ["Fish", "Nuts", "Avocado", "Red meat"],
    ["Protein", "Carbohydrates", "Fat", "Vitamins"],
    ["Blood clotting", "Bone health", "Vision", "Blood pressure regulation"],
    ["Oranges", "Broccoli", "Chicken", "Eggs"],
    ["2 liters", "3 liters", "4 liters", "5 liters"],
    ["Soluble fiber", "Insoluble fiber", "Dietary fiber", "Functional fiber"],
    ["Bone health", "Support nerve function", "Blood clotting", "Muscle contraction"],
    ["Absorbing nutrients", "Digesting fats", "Filtering toxins", "Producing bile"],
    ["Vitamin D", "Vitamin A", "Vitamin K", "Vitamin C"],
    ["0.5g/kg", "1g/kg", "1.5g/kg", "2g/kg"],
    ["Vitamin C", "Vitamin E", "Vitamin A", "Vitamin D"],
    ["Neutralize free radicals", "Prevent dehydration", "Promote digestion", "Enhance taste"],
    ["Carbohydrates", "Protein", "Fat", "Vitamins"],
    ["Maintaining fluid balance", "Regulating heartbeat", "Muscle contraction", "Blood clotting"],
    ["Potassium", "Sodium", "Calcium", "Magnesium"],
    ["25g", "30g", "35g", "40g"],
    ["Soluble fiber dissolves in water, while insoluble fiber does not", "Insoluble fiber dissolves in water, while soluble fiber does not", "Both soluble and insoluble fibers dissolve in water", "Neither soluble nor insoluble fiber dissolves in water"],
    ["Spinach", "Banana", "Chicken", "Yogurt"],
    ["Antioxidant", "Blood clotting", "Immune support", "Vision"],
    ["It measures the impact of a food on blood glucose levels", "It indicates the level of sugar in a food item", "It determines the sweetness of a food", "It assesses the fiber content of a food"],
    ["Calcium", "Vitamin D", "Vitamin C", "Phosphorus"],
    ["Supporting cell structure", "Nerve transmission", "Blood clotting", "Muscle contraction"],
    ["Monounsaturated fat", "Saturated fat", "Polyunsaturated fat", "Trans fat"],
    ["Supporting muscle function", "Providing energy for the brain", "Regulating blood sugar", "Aiding in protein synthesis"],
    ["Vitamin K", "Vitamin C", "Vitamin D", "Vitamin A"],
    ["Aid in digestion", "Promote hydration", "Provide energy", "Enhance taste"],
    ["Salmon", "Nuts", "Spinach", "Chocolate"],
    ["1500mg", "2000mg", "2500mg", "3000mg"],
    ["Water", "Protein", "Fat", "Carbohydrates"],
    ["Protein synthesis", "Wound healing", "Immune support", "Energy production"],
    ["Banana", "Beef", "Peach", "Potato"],
    ["600µg", "800µg", "1000µg", "1200µg"],
    ["Vitamin B9", "Vitamin C", "Vitamin E", "Vitamin A"],
    ["Regulating blood pressure", "Converting food into energy", "Maintaining healthy skin", "Supporting thyroid function"],
    ["Empty calories provide no nutritional value", "Empty calories contain no fat", "Empty calories are high in calories", "Empty calories are low in carbohydrates"],
    ["Fat", "Protein", "Carbohydrates", "Vitamins"],
    ["Nerve function", "Energy metabolism", "DNA synthesis", "Cell division"],
    ["Banana", "Potato", "Avocado", "Milk"],
    ["1200mg", "1000mg", "1100mg", "900mg"],
    ["Iodine", "Zinc", "Copper", "Selenium"],
    ["Promoting bone health", "Enhancing immune response", "Supporting insulin function", "Aiding in glucose metabolism"],
    ["Vitamin A", "Vitamin C", "Vitamin E", "Vitamin K"],
    ["Assisting in blood clotting", "Maintaining healthy skin", "Supporting immune function", "Promoting heart health"],
    ["Kale", "Carrot", "Chicken", "Kiwi"],
    ["60mg", "75mg", "90mg", "100mg"],
    ["Saturated fat", "Monounsaturated fat", "Polyunsaturated fat", "Trans fat"],
    ["Supporting bone health", "Metabolizing carbohydrates", "Aiding in blood clotting", "Promoting antioxidant activity"]
];  

var workoutOptionsArray = [
    ["Weight lifting", "Calisthenics", "Yoga", "Pilates"],
    ["Your stomach", "Your thighs", "Your legs", "Your arms"],
    ["Before you go to bed", "After you wake up", "Right after you exercise", "Right before you exercise"],
    ["Initial, Improvement, Maintenance", "Stretch, Activity, Running", "Training, Monitoring, Cooldown", "Warm-Up, Activity, Cooldown"],
    ["Pull ups", "Light weights", "Weight resistance machines", "The resistance of your own body"],
    ["Repetition", "Frequency", "Intensity", "Volume"],
    ["Plyometrics", "Isometrics", "Resistance training", "Cardio"],
    ["To increase heart rate and circulation", "To prevent muscle soreness", "To enhance flexibility", "To prepare the body for the main workout"],
    ["30 minutes", "45 minutes", "60 minutes", "90 minutes"],
    ["Yoga", "Pilates", "Aerobics", "Zumba"],
    ["15 minutes", "30 minutes", "45 minutes", "60 minutes"],
    ["Improved posture", "Enhanced cardiovascular health", "Increased muscle size", "Strengthened core muscles"],
    ["Static stretching", "Dynamic stretching", "Ballistic stretching", "Proprioceptive neuromuscular facilitation (PNF) stretching"],
    ["1 day", "2 days", "3 days", "4 days"],
    ["Warm-up", "Cooldown", "Interval", "Set"],
    ["Muscular strength", "Muscular endurance", "Flexibility", "Cardiovascular endurance"],
    ["Improves digestion", "Prevents cramps", "Enhances endurance", "Maintains electrolyte balance"],
    ["To lower heart rate", "To gradually bring the body back to a resting state", "To prevent muscle stiffness", "To increase flexibility"],
    ["Bicep curls", "Tricep dips", "Leg press", "Lat pulldowns"],
    ["6-8 reps", "10-12 reps", "15-20 reps", "25-30 reps"],
    ["Flexibility", "Strength", "Endurance", "Balance"],
    ["Controlled breathing", "Increased energy", "Faster recovery", "Improved concentration"],
    ["Running", "Cycling", "Swimming", "Jumping jacks"],
    ["Perceived exhaustion", "Maximum effort", "Muscle soreness", "Fatigue"],
    ["Prevents blisters", "Enhances performance", "Reduces impact on joints", "Improves stability"],
    ["15 minutes", "20 minutes", "30 minutes", "45 minutes"],
    ["Moderate intensity", "Anaerobic zone", "Aerobic zone", "Maximum heart rate"],
    ["Hamstrings", "Quadriceps", "Glutes", "Lower back"],
    ["Proper hydration", "Adequate protein intake", "Quality sleep", "Post-workout stretching"],
    ["Varied workouts", "Enhanced flexibility", "Prevention of boredom", "Increased endurance"],
    ["Improves coordination", "Enhances muscle strength", "Stabilizes joints", "Prevents injuries"],
    ["Plyometrics", "Isometrics", "Isotonic", "Dynamic stretching"],
    ["60 seconds", "90 seconds", "120 seconds", "180 seconds"],
    ["Hamstrings", "Quadriceps", "Calf muscles", "Glutes"],
    ["Immediately before", "After the main workout", "Before and after", "During the workout"],
    ["Dehydration", "Heatstroke", "Heat exhaustion", "Hyponatremia"],
    ["Calcium", "Sodium", "Potassium", "Magnesium"],
    ["Measures workout difficulty", "Assesses muscle soreness", "Estimates calorie burn", "Determines hydration needs"],
    ["Yoga", "Pilates", "Tai Chi", "Aerobics"],
    ["Prevents muscle strain", "Stabilizes the spine", "Improves breathing", "Prevents injuries"],
    ["Cardio", "Strength training", "Flexibility exercises", "Interval training"],
    ["Adequate hydration", "Increased endurance", "Reduced muscle soreness", "Prevention of cramps"],
    ["Providing encouragement", "Ensuring safety", "Assisting with proper form", "Spotting heavyweights"],
    ["Bench press", "Deadlift", "Shoulder press", "Push-up"],
    ["Before the workout", "After the workout", "Before and after the workout", "Anytime during the day"],
    ["3 days", "4 days", "5 days", "7 days"],
    ["Progressive overload", "Interval training", "Circuit training", "Periodization"],
    ["Assessing cardiovascular fitness", "Measuring muscular strength", "Evaluating flexibility", "Analyzing body composition"],
    ["Deltoids", "Pectorals", "Latissimus dorsi", "Triceps"],
    ["Increased muscle mass", "Improved cardiovascular health", "Strengthened bones", "Enhanced endurance"],
    ["Range of motion", "Joint stability", "Joint flexibility", "Joint strength"],
    ["Leg press", "Lunges", "Leg curls", "Squats"],
    ["Prevents dizziness", "Reduces muscle soreness", "Enhances flexibility", "Aids in recovery"],
    ["Balanced workout routine", "Varying exercise intensity", "Consistent warm-up", "Proper form"],
    ["Activating muscles", "Increasing heart rate", "Promoting joint flexibility", "Preparing mentally for the workout"],
    ["Yoga", "Pilates", "Tai Chi", "Zumba"],
];

var anatomyOptionsArray = [
    ["Liver", "Kidney", "Lung", "Heart"],
    ["Femur", "Tibia", "Humerus", "Radius"],
    ["Cerebrum", "Cerebellum", "Medulla oblongata", "Pons"],
    ["Exchange oxygen and carbon dioxide", "Digestion of food", "Filtering blood", "Regulating body temperature"],
    ["Heart", "Lung", "Diaphragm", "Stomach"],
    ["Absorption of nutrients", "Water reabsorption", "Secretion of enzymes", "Storage of waste"],
    ["Ball-and-socket joint", "Hinge joint", "Pivot joint", "Saddle joint"],
    ["Transporting oxygen", "Clotting blood", "Producing antibodies", "Carrying nutrients"],
    ["Thyroid gland", "Adrenal gland", "Pineal gland", "Pituitary gland"],
    ["Cushioning the brain", "Producing hormones", "Generating electricity", "Regulating body temperature"],
    ["Skull", "Ribcage", "Pelvis", "Vertebra"],
    ["Filtering blood", "Regulating blood pressure", "Producing urine", "Storing urine"],
    ["Liver", "Pancreas", "Spleen", "Gallbladder"],
    ["Producing enzymes", "Storing bile", "Absorbing nutrients", "Regulating blood sugar"],
    ["Skeletal muscle", "Cardiac muscle", "Smooth muscle", "Tendon"],
    ["Maintaining fluid balance", "Producing red blood cells", "Digesting fats", "Fighting infections"],
    ["Clavicle", "Femur", "Patella", "Radius"],
    ["Maturing T cells", "Producing antibodies", "Filtering lymph", "Storing red blood cells"],
    ["Cornea", "Pupil", "Lens", "Retina"],
    ["Filtering blood", "Storing platelets", "Producing red blood cells", "Regulating blood pressure"],
    ["Central nervous system", "Peripheral nervous system", "Autonomic nervous system", "Somatic nervous system"],
    ["Protecting the airway during swallowing", "Controlling breathing rate", "Filtering air", "Producing sound"],
    ["Elbow joint", "Hip joint", "Knee joint", "Wrist joint"],
    ["Storing bile", "Digesting fats", "Producing insulin", "Neutralizing stomach acid"],
    ["Deltoid", "Biceps brachii", "Triceps brachii", "Latissimus dorsi"],
    ["Liver", "Skin", "Lung", "Heart"],
    ["Cochlea", "Eardrum", "Auditory canal", "Ossicles"],
    ["Regulating metabolism", "Producing hormones", "Controlling body temperature", "Balancing electrolytes"],
    ["Femur", "Tibia", "Fibula", "Humerus"],
    ["Protection against pathogens", "Producing hormones", "Regulating body temperature", "Eliminating waste"],
    ["Liver", "Stomach", "Pancreas", "Gallbladder"],
    ["Oxygenating blood", "Producing mucus", "Filtering toxins", "Storing nutrients"],
    ["Hippocampus", "Amygdala", "Cerebellum", "Frontal lobe"],
    ["Controlling light refraction", "Focusing on objects", "Detecting color", "Producing tears"],
    ["Skull", "Ribcage", "Vertebra", "Pelvis"],
    ["Conducting air to the lungs", "Producing hormones", "Filtering blood", "Aiding in speech"],
    ["Ball-and-socket joint", "Hinge joint", "Pivot joint", "Saddle joint"],
    ["Lubricating joints", "Supplying nutrients to bones", "Providing support", "Absorbing shock"],
    ["Biceps brachii", "Triceps brachii", "Deltoid", "Quadriceps femoris"],
    ["Regulating blood pressure", "Controlling stress response", "Balancing electrolytes", "Producing adrenaline"],
    ["Small intestine", "Stomach", "Colon", "Esophagus"],
    ["Reproduction", "Filtering toxins", "Maintaining electrolyte balance", "Producing hormones"],
    ["Sacrum", "Coccyx", "Ilium", "Ischium"],
    ["Coordinating voluntary movements", "Regulating metabolism", "Producing hormones", "Stimulating muscle contractions"],
    ["Retina", "Cornea", "Lens", "Optic nerve"],
    ["Producing sperm", "Facilitating childbirth", "Producing testosterone", "Generating urine"],
    ["Kidney", "Liver", "Heart", "Lung"],
    ["Protecting the brain", "Generating electricity", "Cushioning the spinal cord", "Producing cerebrospinal fluid"],
    ["Ball-and-socket joint", "Hinge joint", "Pivot joint", "Saddle joint"],
];

var colors = ["rgb(5, 184, 184)", "yellow", "green", "orange", "purple", "Coral", "Lavender", "Magenta", "Teal"];

var randomBackgrounds = [
    "ProjectMedia/ProjectPictures/QuizPictures/spaceOne.jpg", 
    "ProjectMedia/ProjectPictures/QuizPictures/spaceTwo.jpg", 
    "ProjectMedia/ProjectPictures/QuizPictures/spaceThree.jpg", 
    "ProjectMedia/ProjectPictures/QuizPictures/spaceFour.jpg", 
    "ProjectMedia/ProjectPictures/QuizPictures/spaceFive.jpg", 
    "ProjectMedia/ProjectPictures/QuizPictures/spaceSix.jpg",
    "ProjectMedia/ProjectPictures/QuizPictures/spaceSeven.jpg",
    "ProjectMedia/ProjectPictures/QuizPictures/spaceEight.jpg",
    "ProjectMedia/ProjectPictures/QuizPictures/spaceNine.jpg",
    "ProjectMedia/ProjectPictures/QuizPictures/spaceTen.jpg",
];